// This file is auto-generated by @hey-api/openapi-ts

export { getAuthByProviderCallback, getAuthByProviderLogin, type Options } from './sdk.gen';
export type { AuthResponse, ClientOptions, Error, GetAuthByProviderCallbackData, GetAuthByProviderCallbackError, GetAuthByProviderCallbackErrors, GetAuthByProviderCallbackResponse, GetAuthByProviderCallbackResponses, GetAuthByProviderLoginData, GetAuthByProviderLoginError, GetAuthByProviderLoginErrors, User } from './types.gen';
