// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiAuthByProviderCallbackData, GetApiAuthByProviderCallbackErrors, GetApiAuthByProviderCallbackResponses, GetApiAuthByProviderLoginData, GetApiAuthByProviderLoginErrors, GetApiAuthMeData, GetApiAuthMeErrors, GetApiAuthMeResponses, GetApiGamesByIdData, GetApiGamesByIdErrors, GetApiGamesByIdResponses, PatchApiGamesByIdData, PatchApiGamesByIdErrors, PatchApiGamesByIdResponses, PostApiGamesData, PostApiGamesErrors, PostApiGamesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Initiate OAuth login with a provider
 *
 * Redirects the user to the OAuth provider's authorization page
 */
export const getApiAuthByProviderLogin = <ThrowOnError extends boolean = false>(options: Options<GetApiAuthByProviderLoginData, ThrowOnError>) => (options.client ?? client).get<unknown, GetApiAuthByProviderLoginErrors, ThrowOnError>({ url: '/api/auth/{provider}/login', ...options });

/**
 * OAuth callback endpoint
 *
 * Handles the OAuth provider's redirect after user grants or denies authorization
 */
export const getApiAuthByProviderCallback = <ThrowOnError extends boolean = false>(options: Options<GetApiAuthByProviderCallbackData, ThrowOnError>) => (options.client ?? client).get<GetApiAuthByProviderCallbackResponses, GetApiAuthByProviderCallbackErrors, ThrowOnError>({ url: '/api/auth/{provider}/callback', ...options });

/**
 * Get authenticated user
 *
 * Returns the currently authenticated user
 */
export const getApiAuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetApiAuthMeData, ThrowOnError>) => (options?.client ?? client).get<GetApiAuthMeResponses, GetApiAuthMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/me',
    ...options
});

/**
 * Create a new game
 *
 * Creates a new game. The game is only visible to the organizer initially unless publish is set to true.
 */
export const postApiGames = <ThrowOnError extends boolean = false>(options: Options<PostApiGamesData, ThrowOnError>) => (options.client ?? client).post<PostApiGamesResponses, PostApiGamesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/games',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a game by ID
 *
 * Retrieves a single game by its ID
 */
export const getApiGamesById = <ThrowOnError extends boolean = false>(options: Options<GetApiGamesByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiGamesByIdResponses, GetApiGamesByIdErrors, ThrowOnError>({ url: '/api/games/{id}', ...options });

/**
 * Update a game
 *
 * Updates an existing game. Only the organizer can update their game.
 */
export const patchApiGamesById = <ThrowOnError extends boolean = false>(options: Options<PatchApiGamesByIdData, ThrowOnError>) => (options.client ?? client).patch<PatchApiGamesByIdResponses, PatchApiGamesByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/games/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
