// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiAuthByProviderCallbackData, GetApiAuthByProviderCallbackErrors, GetApiAuthByProviderCallbackResponses, GetApiAuthByProviderLoginData, GetApiAuthByProviderLoginErrors, GetApiAuthMeData, GetApiAuthMeErrors, GetApiAuthMeResponses, GetApiDemoUsersData, GetApiDemoUsersErrors, GetApiDemoUsersResponses, GetApiGamesByIdData, GetApiGamesByIdErrors, GetApiGamesByIdParticipantsData, GetApiGamesByIdParticipantsErrors, GetApiGamesByIdParticipantsResponses, GetApiGamesByIdResponses, GetApiGamesData, GetApiGamesErrors, GetApiGamesResponses, PatchApiGamesByIdData, PatchApiGamesByIdErrors, PatchApiGamesByIdResponses, PostApiAuthLogoutData, PostApiAuthLogoutErrors, PostApiAuthLogoutResponses, PostApiDemoUsersByUserIdImpersonateData, PostApiDemoUsersByUserIdImpersonateErrors, PostApiDemoUsersByUserIdImpersonateResponses, PostApiGamesByIdParticipantsData, PostApiGamesByIdParticipantsErrors, PostApiGamesByIdParticipantsResponses, PostApiGamesData, PostApiGamesErrors, PostApiGamesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Initiate OAuth login with a provider
 *
 * Redirects the user to the OAuth provider's authorization page
 */
export const getApiAuthByProviderLogin = <ThrowOnError extends boolean = false>(options: Options<GetApiAuthByProviderLoginData, ThrowOnError>) => (options.client ?? client).get<unknown, GetApiAuthByProviderLoginErrors, ThrowOnError>({ url: '/api/auth/{provider}/login', ...options });

/**
 * OAuth callback endpoint
 *
 * Handles the OAuth provider's redirect after user grants or denies authorization
 */
export const getApiAuthByProviderCallback = <ThrowOnError extends boolean = false>(options: Options<GetApiAuthByProviderCallbackData, ThrowOnError>) => (options.client ?? client).get<GetApiAuthByProviderCallbackResponses, GetApiAuthByProviderCallbackErrors, ThrowOnError>({ url: '/api/auth/{provider}/callback', ...options });

/**
 * Get authenticated user
 *
 * Returns the currently authenticated user
 */
export const getApiAuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetApiAuthMeData, ThrowOnError>) => (options?.client ?? client).get<GetApiAuthMeResponses, GetApiAuthMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/me',
    ...options
});

/**
 * Logout the authenticated user
 *
 * Clears the authentication token and logs out the user
 */
export const postApiAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthLogoutData, ThrowOnError>) => (options?.client ?? client).post<PostApiAuthLogoutResponses, PostApiAuthLogoutErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/logout',
    ...options
});

/**
 * Impersonate a demo user
 *
 * opengym can be started in demo mode, in which case authentication is replaced with impersonation of a demo user
 */
export const postApiDemoUsersByUserIdImpersonate = <ThrowOnError extends boolean = false>(options: Options<PostApiDemoUsersByUserIdImpersonateData, ThrowOnError>) => (options.client ?? client).post<PostApiDemoUsersByUserIdImpersonateResponses, PostApiDemoUsersByUserIdImpersonateErrors, ThrowOnError>({ url: '/api/demo/users/{userId}/impersonate', ...options });

/**
 * List demo users
 *
 * Returns all demo users
 */
export const getApiDemoUsers = <ThrowOnError extends boolean = false>(options?: Options<GetApiDemoUsersData, ThrowOnError>) => (options?.client ?? client).get<GetApiDemoUsersResponses, GetApiDemoUsersErrors, ThrowOnError>({ url: '/api/demo/users', ...options });

/**
 * List user's games
 *
 * Returns all games the authenticated user is either organizing or participating in
 */
export const getApiGames = <ThrowOnError extends boolean = false>(options?: Options<GetApiGamesData, ThrowOnError>) => (options?.client ?? client).get<GetApiGamesResponses, GetApiGamesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/games',
    ...options
});

/**
 * Create a new game
 *
 * Creates a new game. The game is created as a draft and is only visible to the organizer until it is published via the update endpoint.
 */
export const postApiGames = <ThrowOnError extends boolean = false>(options: Options<PostApiGamesData, ThrowOnError>) => (options.client ?? client).post<PostApiGamesResponses, PostApiGamesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/games',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a game by ID
 *
 * Retrieves a single game by its ID
 */
export const getApiGamesById = <ThrowOnError extends boolean = false>(options: Options<GetApiGamesByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiGamesByIdResponses, GetApiGamesByIdErrors, ThrowOnError>({ url: '/api/games/{id}', ...options });

/**
 * Update a game
 *
 * Updates an existing game. Only the organizer can update their game. Publishing is irreversible once the publish time has passed. If `publishedAt` is in the future, the organizer may reschedule it or cancel publishing (unset the field) until it becomes effective.
 */
export const patchApiGamesById = <ThrowOnError extends boolean = false>(options: Options<PatchApiGamesByIdData, ThrowOnError>) => (options.client ?? client).patch<PatchApiGamesByIdResponses, PatchApiGamesByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/games/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List game participants
 *
 * Returns all participants for the specified game with their computed participation status. The status is computed based on the order participants signed up (going) and the max_players limit.
 */
export const getApiGamesByIdParticipants = <ThrowOnError extends boolean = false>(options: Options<GetApiGamesByIdParticipantsData, ThrowOnError>) => (options.client ?? client).get<GetApiGamesByIdParticipantsResponses, GetApiGamesByIdParticipantsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/games/{id}/participants',
    ...options
});

/**
 * Set participation status
 *
 * Creates or updates the authenticated user's participation status for the specified game.
 */
export const postApiGamesByIdParticipants = <ThrowOnError extends boolean = false>(options: Options<PostApiGamesByIdParticipantsData, ThrowOnError>) => (options.client ?? client).post<PostApiGamesByIdParticipantsResponses, PostApiGamesByIdParticipantsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/games/{id}/participants',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
