// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type AuthResponse = {
    /**
     * JWT or session token for authenticating subsequent requests
     */
    token: string;
    /**
     * Optional refresh token for obtaining new access tokens
     */
    refreshToken?: string;
    /**
     * Token expiration time in seconds
     */
    expiresIn?: number;
    user: User;
};

export type User = {
    /**
     * Unique user identifier
     */
    id: string;
    /**
     * User's email address
     */
    email: string;
    /**
     * User's full name
     */
    name?: string;
    /**
     * URL to user's profile picture
     */
    picture?: string;
    /**
     * OAuth provider used for authentication
     */
    provider: 'google';
    /**
     * Timestamp when user was created
     */
    createdAt?: string;
    /**
     * Timestamp when user was last updated
     */
    updatedAt?: string;
};

export type CreateGameRequest = {
    /**
     * Name of the game
     */
    name: string;
    /**
     * Description of the game
     */
    description?: string;
    /**
     * Total price in cents
     */
    totalPriceCents?: number;
    /**
     * Location where the game will be held
     */
    location?: string;
    /**
     * When the game starts
     */
    startsAt?: string;
    /**
     * Duration of the game in minutes
     */
    durationMinutes?: number;
    /**
     * Maximum number of players (-1 for unlimited)
     */
    maxPlayers?: number;
    /**
     * Maximum waitlist size (0 to disable, -1 for unlimited)
     */
    maxWaitlistSize?: number;
    /**
     * Maximum guests per player (0 to disable, -1 for unlimited)
     */
    maxGuestsPerPlayer?: number;
};

export type UpdateGameRequest = {
    /**
     * Name of the game
     */
    name?: string;
    /**
     * Description of the game
     */
    description?: string;
    /**
     * Whether to make the game publicly visible
     */
    publish?: boolean;
    /**
     * Total price in cents
     */
    totalPriceCents?: number;
    /**
     * Location where the game will be held
     */
    location?: string;
    /**
     * When the game starts
     */
    startsAt?: string;
    /**
     * Duration of the game in minutes
     */
    durationMinutes?: number;
    /**
     * Maximum number of players (-1 for unlimited)
     */
    maxPlayers?: number;
    /**
     * Maximum waitlist size (0 to disable, -1 for unlimited)
     */
    maxWaitlistSize?: number;
    /**
     * Maximum guests per player (0 to disable, -1 for unlimited)
     */
    maxGuestsPerPlayer?: number;
};

export type Game = {
    /**
     * Unique game identifier
     */
    id: string;
    /**
     * ID of the user who organized the game
     */
    organizerId: number;
    /**
     * Name of the game
     */
    name: string;
    /**
     * Description of the game
     */
    description?: string;
    /**
     * When the game is published (visible to others)
     */
    publishedAt?: string;
    /**
     * Total price in cents
     */
    totalPriceCents?: number;
    /**
     * Location where the game will be held
     */
    location?: string;
    /**
     * When the game starts
     */
    startsAt?: string;
    /**
     * Duration of the game in minutes
     */
    durationMinutes?: number;
    /**
     * Maximum number of players (-1 for unlimited)
     */
    maxPlayers?: number;
    /**
     * Maximum waitlist size (0 to disable, -1 for unlimited)
     */
    maxWaitlistSize?: number;
    /**
     * Maximum guests per player (0 to disable, -1 for unlimited)
     */
    maxGuestsPerPlayer?: number;
    /**
     * Timestamp when game was created
     */
    createdAt: string;
    /**
     * Timestamp when game was last updated
     */
    updatedAt: string;
};

/**
 * Error message string
 */
export type Error = string;

export type GetApiAuthByProviderLoginData = {
    body?: never;
    path: {
        /**
         * The OAuth provider to use for authentication
         */
        provider: 'google';
    };
    query?: never;
    url: '/api/auth/{provider}/login';
};

export type GetApiAuthByProviderLoginErrors = {
    /**
     * Invalid provider specified
     */
    400: Error;
};

export type GetApiAuthByProviderLoginError = GetApiAuthByProviderLoginErrors[keyof GetApiAuthByProviderLoginErrors];

export type GetApiAuthByProviderCallbackData = {
    body?: never;
    path: {
        /**
         * The OAuth provider
         */
        provider: 'google';
    };
    query?: {
        /**
         * Authorization code returned by the provider on success
         */
        code?: string;
        /**
         * State parameter for CSRF protection
         */
        state?: string;
        /**
         * Error code if authorization failed
         */
        error?: string;
        /**
         * Human-readable error description
         */
        error_description?: string;
    };
    url: '/api/auth/{provider}/callback';
};

export type GetApiAuthByProviderCallbackErrors = {
    /**
     * Invalid request or error from provider
     */
    400: Error;
    /**
     * Authentication failed
     */
    401: Error;
};

export type GetApiAuthByProviderCallbackError = GetApiAuthByProviderCallbackErrors[keyof GetApiAuthByProviderCallbackErrors];

export type GetApiAuthByProviderCallbackResponses = {
    /**
     * Successfully authenticated user
     */
    200: AuthResponse;
};

export type GetApiAuthByProviderCallbackResponse = GetApiAuthByProviderCallbackResponses[keyof GetApiAuthByProviderCallbackResponses];

export type PostApiGamesData = {
    body: CreateGameRequest;
    path?: never;
    query?: never;
    url: '/api/games';
};

export type PostApiGamesErrors = {
    /**
     * Invalid request data
     */
    400: Error;
    /**
     * Unauthorized - invalid or missing token
     */
    401: Error;
};

export type PostApiGamesError = PostApiGamesErrors[keyof PostApiGamesErrors];

export type PostApiGamesResponses = {
    /**
     * Game created successfully
     */
    200: Game;
};

export type PostApiGamesResponse = PostApiGamesResponses[keyof PostApiGamesResponses];

export type PatchApiGamesByIdData = {
    body: UpdateGameRequest;
    path: {
        /**
         * The game ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{id}';
};

export type PatchApiGamesByIdErrors = {
    /**
     * Invalid request data
     */
    400: Error;
    /**
     * Unauthorized - invalid or missing token
     */
    401: Error;
    /**
     * Forbidden - not the game organizer
     */
    403: Error;
    /**
     * Game not found
     */
    404: Error;
};

export type PatchApiGamesByIdError = PatchApiGamesByIdErrors[keyof PatchApiGamesByIdErrors];

export type PatchApiGamesByIdResponses = {
    /**
     * Game updated successfully
     */
    200: Game;
};

export type PatchApiGamesByIdResponse = PatchApiGamesByIdResponses[keyof PatchApiGamesByIdResponses];
