// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type AuthResponse = {
    /**
     * JWT or session token for authenticating subsequent requests
     */
    token: string;
    /**
     * Optional refresh token for obtaining new access tokens
     */
    refreshToken?: string;
    /**
     * Token expiration time in seconds
     */
    expiresIn?: number;
    user: User;
};

export type User = {
    /**
     * Unique user identifier
     */
    id: string;
    /**
     * User's email address
     */
    email: string;
    /**
     * User's full name
     */
    name?: string;
    /**
     * URL to user's profile picture
     */
    picture?: string;
    /**
     * Timestamp when user was created
     */
    createdAt?: string;
    /**
     * Timestamp when user was last updated
     */
    updatedAt?: string;
    /**
     * Whether the user is a demo user
     */
    isDemo: boolean;
};

export type GameFields = {
    /**
     * Name of the game
     */
    name?: string;
    /**
     * Description of the game
     */
    description?: string;
    /**
     * Total price in cents
     */
    totalPriceCents?: number;
    /**
     * Location where the game will be held
     */
    location?: string;
    /**
     * When the game starts
     */
    startsAt?: string;
    /**
     * Duration of the game in minutes
     */
    durationMinutes?: number;
    /**
     * Maximum number of players (must be at least 1)
     */
    maxPlayers?: number;
    /**
     * Maximum guests per player (0 to disable)
     */
    maxGuestsPerPlayer?: number;
    /**
     * Number of spots left in the game, excluding the waitlist
     */
    gameSpotsLeft?: number;
};

export type CreateGameRequest = GameFields & {
    [key: string]: unknown;
};

export type UpdateGameRequest = GameFields & {
    /**
     * When the game should become publicly visible. Past timestamps publish immediately. While in the future, it can be rescheduled or cleared.
     */
    publishedAt?: string | null;
};

export type Game = GameFields & {
    /**
     * Unique game identifier
     */
    id: string;
    /**
     * ID of the user who organized the game
     */
    organizerId: number;
    /**
     * When the game is published (visible to others)
     */
    publishedAt?: string;
    /**
     * Timestamp when game was created
     */
    createdAt: string;
    /**
     * Timestamp when game was last updated
     */
    updatedAt: string;
};

export type GameDetail = {
    game: Game;
    organizer: User;
};

/**
 * Participation status of the authenticated user
 */
export type ParticipationStatus = ParticipationStatusUpdate | 'waitlisted';

/**
 * Allowed participation statuses that a user can set directly
 */
export type ParticipationStatusUpdate = 'going' | 'not_going';

export type GameParticipation = {
    status: ParticipationStatus;
    /**
     * Identifier of the participant
     */
    userId: string;
    /**
     * Identifier of the game
     */
    gameId: string;
    /**
     * Timestamp when the participation record was created
     */
    createdAt?: string;
    /**
     * Timestamp when the participation record was last updated
     */
    updatedAt?: string;
};

export type ParticipantWithUser = {
    status: ParticipationStatus;
    /**
     * Number of guests the participant is bringing
     */
    guests: number;
    user: User;
    /**
     * Timestamp when the participation record was created
     */
    createdAt?: string;
    /**
     * Timestamp when the participation record was last updated
     */
    updatedAt?: string;
};

export type UpdateGameParticipationRequest = {
    status: ParticipationStatusUpdate;
    /**
     * If the participant has confirmed (can only be set to false by the server when important details are changed on the game)
     */
    confirmed?: true;
    /**
     * Number of guests the participant is bringing
     */
    guests?: number;
};

export type GameListItem = {
    /**
     * Unique game identifier
     */
    id: string;
    /**
     * Name of the game
     */
    name: string;
    /**
     * Whether the authenticated user is the organizer of this game
     */
    isOrganizer: boolean;
    organizer: User;
    /**
     * Location where the game will be held
     */
    location?: string;
    /**
     * When the game starts
     */
    startsAt?: string | null;
    /**
     * When the game is published (visible to others)
     */
    publishedAt?: string | null;
    /**
     * Timestamp when game was last updated
     */
    updatedAt: string;
};

export type Pagination = {
    /**
     * Total number of items
     */
    total: number;
    /**
     * Current page number (1-based)
     */
    page: number;
    /**
     * Number of items per page
     */
    pageSize: number;
};

export type GameListResponse = Pagination & {
    /**
     * Array of games for the current page
     */
    items: Array<GameListItem>;
};

/**
 * Error message string
 */
export type Error = string;

export type GetApiAuthByProviderLoginData = {
    body?: never;
    path: {
        /**
         * The OAuth provider to use for authentication
         */
        provider: 'google';
    };
    query?: never;
    url: '/api/auth/{provider}/login';
};

export type GetApiAuthByProviderLoginErrors = {
    /**
     * Invalid provider specified
     */
    400: Error;
};

export type GetApiAuthByProviderLoginError = GetApiAuthByProviderLoginErrors[keyof GetApiAuthByProviderLoginErrors];

export type GetApiAuthByProviderCallbackData = {
    body?: never;
    path: {
        /**
         * The OAuth provider
         */
        provider: 'google';
    };
    query?: {
        /**
         * Authorization code returned by the provider on success
         */
        code?: string;
        /**
         * State parameter for CSRF protection
         */
        state?: string;
        /**
         * Error code if authorization failed
         */
        error?: string;
        /**
         * Human-readable error description
         */
        error_description?: string;
    };
    url: '/api/auth/{provider}/callback';
};

export type GetApiAuthByProviderCallbackErrors = {
    /**
     * Invalid request or error from provider
     */
    400: Error;
    /**
     * Authentication failed
     */
    401: Error;
};

export type GetApiAuthByProviderCallbackError = GetApiAuthByProviderCallbackErrors[keyof GetApiAuthByProviderCallbackErrors];

export type GetApiAuthByProviderCallbackResponses = {
    /**
     * Successfully authenticated user
     */
    200: AuthResponse;
};

export type GetApiAuthByProviderCallbackResponse = GetApiAuthByProviderCallbackResponses[keyof GetApiAuthByProviderCallbackResponses];

export type GetApiAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetApiAuthMeErrors = {
    /**
     * Unauthorized - invalid or missing token
     */
    401: Error;
};

export type GetApiAuthMeError = GetApiAuthMeErrors[keyof GetApiAuthMeErrors];

export type GetApiAuthMeResponses = {
    /**
     * Authenticated user
     */
    200: User;
};

export type GetApiAuthMeResponse = GetApiAuthMeResponses[keyof GetApiAuthMeResponses];

export type PostApiAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type PostApiAuthLogoutErrors = {
    /**
     * Unauthorized - invalid or missing token
     */
    401: Error;
};

export type PostApiAuthLogoutError = PostApiAuthLogoutErrors[keyof PostApiAuthLogoutErrors];

export type PostApiAuthLogoutResponses = {
    /**
     * Successfully logged out
     */
    204: void;
};

export type PostApiAuthLogoutResponse = PostApiAuthLogoutResponses[keyof PostApiAuthLogoutResponses];

export type PostApiDemoUsersByUserIdImpersonateData = {
    body?: never;
    path: {
        /**
         * ID of the demo user to impersonate
         */
        userId: string;
    };
    query?: never;
    url: '/api/demo/users/{userId}/impersonate';
};

export type PostApiDemoUsersByUserIdImpersonateErrors = {
    /**
     * The back-end was not started in demo mode so this endpoint is disabled.
     */
    403: Error;
};

export type PostApiDemoUsersByUserIdImpersonateError = PostApiDemoUsersByUserIdImpersonateErrors[keyof PostApiDemoUsersByUserIdImpersonateErrors];

export type PostApiDemoUsersByUserIdImpersonateResponses = {
    /**
     * Successfully impersonated demo user
     */
    200: User;
};

export type PostApiDemoUsersByUserIdImpersonateResponse = PostApiDemoUsersByUserIdImpersonateResponses[keyof PostApiDemoUsersByUserIdImpersonateResponses];

export type GetApiDemoUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/demo/users';
};

export type GetApiDemoUsersErrors = {
    /**
     * The back-end was not started in demo mode so this endpoint is disabled.
     */
    403: Error;
};

export type GetApiDemoUsersError = GetApiDemoUsersErrors[keyof GetApiDemoUsersErrors];

export type GetApiDemoUsersResponses = {
    /**
     * List of demo users retrieved successfully
     */
    200: Array<User>;
};

export type GetApiDemoUsersResponse = GetApiDemoUsersResponses[keyof GetApiDemoUsersResponses];

export type GetApiGamesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-based) for pagination
         */
        page?: number;
        /**
         * Number of games per page (max 25)
         */
        pageSize?: number;
    };
    url: '/api/games';
};

export type GetApiGamesErrors = {
    /**
     * Unauthorized - invalid or missing token
     */
    401: Error;
};

export type GetApiGamesError = GetApiGamesErrors[keyof GetApiGamesErrors];

export type GetApiGamesResponses = {
    /**
     * List of games retrieved successfully
     */
    200: GameListResponse;
};

export type GetApiGamesResponse = GetApiGamesResponses[keyof GetApiGamesResponses];

export type PostApiGamesData = {
    body: CreateGameRequest;
    path?: never;
    query?: never;
    url: '/api/games';
};

export type PostApiGamesErrors = {
    /**
     * Invalid request data
     */
    400: Error;
    /**
     * Unauthorized - invalid or missing token
     */
    401: Error;
};

export type PostApiGamesError = PostApiGamesErrors[keyof PostApiGamesErrors];

export type PostApiGamesResponses = {
    /**
     * Game created successfully
     */
    200: GameDetail;
};

export type PostApiGamesResponse = PostApiGamesResponses[keyof PostApiGamesResponses];

export type GetApiGamesByIdData = {
    body?: never;
    path: {
        /**
         * The game ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{id}';
};

export type GetApiGamesByIdErrors = {
    /**
     * Game not found
     */
    404: Error;
};

export type GetApiGamesByIdError = GetApiGamesByIdErrors[keyof GetApiGamesByIdErrors];

export type GetApiGamesByIdResponses = {
    /**
     * Game retrieved successfully
     */
    200: GameDetail;
};

export type GetApiGamesByIdResponse = GetApiGamesByIdResponses[keyof GetApiGamesByIdResponses];

export type PatchApiGamesByIdData = {
    body: UpdateGameRequest;
    path: {
        /**
         * The game ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{id}';
};

export type PatchApiGamesByIdErrors = {
    /**
     * Invalid request data
     */
    400: Error;
    /**
     * Unauthorized - invalid or missing token
     */
    401: Error;
    /**
     * Forbidden - not the game organizer
     */
    403: Error;
    /**
     * Game not found
     */
    404: Error;
};

export type PatchApiGamesByIdError = PatchApiGamesByIdErrors[keyof PatchApiGamesByIdErrors];

export type PatchApiGamesByIdResponses = {
    /**
     * Game updated successfully
     */
    200: GameDetail;
};

export type PatchApiGamesByIdResponse = PatchApiGamesByIdResponses[keyof PatchApiGamesByIdResponses];

export type GetApiGamesByIdParticipantsData = {
    body?: never;
    path: {
        /**
         * The game ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{id}/participants';
};

export type GetApiGamesByIdParticipantsErrors = {
    /**
     * Unauthorized - invalid or missing token
     */
    401: Error;
    /**
     * Game not found
     */
    404: Error;
};

export type GetApiGamesByIdParticipantsError = GetApiGamesByIdParticipantsErrors[keyof GetApiGamesByIdParticipantsErrors];

export type GetApiGamesByIdParticipantsResponses = {
    /**
     * List of participants retrieved successfully
     */
    200: Array<ParticipantWithUser>;
};

export type GetApiGamesByIdParticipantsResponse = GetApiGamesByIdParticipantsResponses[keyof GetApiGamesByIdParticipantsResponses];

export type PostApiGamesByIdParticipantsData = {
    body: UpdateGameParticipationRequest;
    path: {
        /**
         * The game ID
         */
        id: string;
    };
    query?: never;
    url: '/api/games/{id}/participants';
};

export type PostApiGamesByIdParticipantsErrors = {
    /**
     * Invalid request data
     */
    400: Error;
    /**
     * Unauthorized - invalid or missing token
     */
    401: Error;
    /**
     * Game not found
     */
    404: Error;
};

export type PostApiGamesByIdParticipantsError = PostApiGamesByIdParticipantsErrors[keyof PostApiGamesByIdParticipantsErrors];

export type PostApiGamesByIdParticipantsResponses = {
    /**
     * Participation status updated successfully
     */
    200: GameParticipation;
};

export type PostApiGamesByIdParticipantsResponse = PostApiGamesByIdParticipantsResponses[keyof PostApiGamesByIdParticipantsResponses];
