// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Game struct {
	ID                 string
	OrganizerID        int64
	Name               string
	Description        sql.NullString
	PublishedAt        sql.NullTime
	TotalPriceCents    int64
	Location           sql.NullString
	StartsAt           sql.NullTime
	DurationMinutes    int64
	MaxPlayers         int64
	MaxWaitlistSize    int64
	MaxGuestsPerPlayer int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type GameParticipant struct {
	UserID         int64
	GameID         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	GoingUpdatedAt time.Time
	Going          sql.NullBool
	ConfirmedAt    sql.NullTime
	Guests         sql.NullInt64
}

type User struct {
	ID        int64
	Name      sql.NullString
	Email     string
	Photo     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	IsDemo    bool
}
