// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participants.sql

package db

import (
	"context"
	"database/sql"
)

const participantsUpsert = `-- name: ParticipantsUpsert :exec
insert into game_participants(
    user_id,
    game_id,
    created_at,
    updated_at,
    going,
    confirmed
) values (?, ?, current_timestamp, current_timestamp, ?, ?)
on conflict(user_id, game_id) do update set
    updated_at = current_timestamp,
    going = coalesce(excluded.going, game_participants.going),
    confirmed = coalesce(excluded.confirmed, game_participants.confirmed)
`

type ParticipantsUpsertParams struct {
	UserID    int64
	GameID    string
	Going     sql.NullBool
	Confirmed sql.NullBool
}

func (q *Queries) ParticipantsUpsert(ctx context.Context, arg ParticipantsUpsertParams) error {
	_, err := q.db.ExecContext(ctx, participantsUpsert,
		arg.UserID,
		arg.GameID,
		arg.Going,
		arg.Confirmed,
	)
	return err
}
