// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participants.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const participantGetByGameAndUser = `-- name: ParticipantGetByGameAndUser :one
select user_id, game_id, created_at, updated_at, going_updated_at, going, confirmed_at, guests, reimbursed_at, reimbursement_received_at, reimbursement_reference
from game_participants
where game_id = ?1
    and user_id = ?2
`

type ParticipantGetByGameAndUserParams struct {
	GameID string
	UserID int64
}

func (q *Queries) ParticipantGetByGameAndUser(ctx context.Context, arg ParticipantGetByGameAndUserParams) (GameParticipant, error) {
	row := q.db.QueryRowContext(ctx, participantGetByGameAndUser, arg.GameID, arg.UserID)
	var i GameParticipant
	err := row.Scan(
		&i.UserID,
		&i.GameID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoingUpdatedAt,
		&i.Going,
		&i.ConfirmedAt,
		&i.Guests,
		&i.ReimbursedAt,
		&i.ReimbursementReceivedAt,
		&i.ReimbursementReference,
	)
	return i, err
}

const participantUpdateReimbursedAt = `-- name: ParticipantUpdateReimbursedAt :execrows
update game_participants
set
        updated_at = current_timestamp,
        reimbursed_at = ?1
where game_id = ?2
    and user_id = ?3
`

type ParticipantUpdateReimbursedAtParams struct {
	ReimbursedAt sql.NullTime
	GameID       string
	UserID       int64
}

func (q *Queries) ParticipantUpdateReimbursedAt(ctx context.Context, arg ParticipantUpdateReimbursedAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, participantUpdateReimbursedAt, arg.ReimbursedAt, arg.GameID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const participantUpdateReimbursementReceivedAt = `-- name: ParticipantUpdateReimbursementReceivedAt :execrows
update game_participants
set
        updated_at = current_timestamp,
        reimbursement_received_at = ?1
where game_id = ?2
    and user_id = ?3
`

type ParticipantUpdateReimbursementReceivedAtParams struct {
	ReimbursementReceivedAt sql.NullTime
	GameID                  string
	UserID                  int64
}

func (q *Queries) ParticipantUpdateReimbursementReceivedAt(ctx context.Context, arg ParticipantUpdateReimbursementReceivedAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, participantUpdateReimbursementReceivedAt, arg.ReimbursementReceivedAt, arg.GameID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const participantsList = `-- name: ParticipantsList :many
select
    users.id = ?1 as is_organizer,
    game_participants.user_id, game_participants.game_id, game_participants.created_at, game_participants.updated_at, game_participants.going_updated_at, game_participants.going, game_participants.confirmed_at, game_participants.guests, game_participants.reimbursed_at, game_participants.reimbursement_received_at, game_participants.reimbursement_reference,
    users.id, users.name, users.email, users.photo, users.created_at, users.updated_at, users.is_demo
from game_participants
join users on game_participants.user_id = users.id
where game_participants.game_id = ?2
order by
    1 desc, -- if the user is the organizer, they should have priority
    game_participants.going_updated_at asc
`

type ParticipantsListParams struct {
	OrganizerID int64
	GameID      string
}

type ParticipantsListRow struct {
	IsOrganizer     bool
	GameParticipant GameParticipant
	User            User
}

func (q *Queries) ParticipantsList(ctx context.Context, arg ParticipantsListParams) ([]ParticipantsListRow, error) {
	rows, err := q.db.QueryContext(ctx, participantsList, arg.OrganizerID, arg.GameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParticipantsListRow
	for rows.Next() {
		var i ParticipantsListRow
		if err := rows.Scan(
			&i.IsOrganizer,
			&i.GameParticipant.UserID,
			&i.GameParticipant.GameID,
			&i.GameParticipant.CreatedAt,
			&i.GameParticipant.UpdatedAt,
			&i.GameParticipant.GoingUpdatedAt,
			&i.GameParticipant.Going,
			&i.GameParticipant.ConfirmedAt,
			&i.GameParticipant.Guests,
			&i.GameParticipant.ReimbursedAt,
			&i.GameParticipant.ReimbursementReceivedAt,
			&i.GameParticipant.ReimbursementReference,
			&i.User.ID,
			&i.User.Name,
			&i.User.Email,
			&i.User.Photo,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.IsDemo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const participantsUpsert = `-- name: ParticipantsUpsert :exec
insert into game_participants(
    user_id,
    game_id,
    going,
    going_updated_at,
    confirmed_at,
    guests
) values (?, ?, ?, ?, ?, ?)
on conflict(user_id, game_id) do update set
    updated_at = current_timestamp,
    going = coalesce(excluded.going, game_participants.going),
    -- we only update going_updated_at if a field relevant to a participant's order in the queue has changed
    going_updated_at = iif(
        excluded.going = game_participants.going and (excluded.guests is null or excluded.guests is game_participants.guests),
        game_participants.going_updated_at,
        excluded.going_updated_at
    ),
    confirmed_at = coalesce(excluded.confirmed_at, game_participants.confirmed_at),
    guests = coalesce(excluded.guests, game_participants.guests)
`

type ParticipantsUpsertParams struct {
	UserID         int64
	GameID         string
	Going          sql.NullBool
	GoingUpdatedAt time.Time
	ConfirmedAt    sql.NullTime
	Guests         sql.NullInt64
}

func (q *Queries) ParticipantsUpsert(ctx context.Context, arg ParticipantsUpsertParams) error {
	_, err := q.db.ExecContext(ctx, participantsUpsert,
		arg.UserID,
		arg.GameID,
		arg.Going,
		arg.GoingUpdatedAt,
		arg.ConfirmedAt,
		arg.Guests,
	)
	return err
}
