// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GameCreate(ctx context.Context, arg GameCreateParams) (Game, error)
	GameGetById(ctx context.Context, id string) (Game, error)
	GameUpdate(ctx context.Context, arg GameUpdateParams) error
	UserUpsertRetuningId(ctx context.Context, arg UserUpsertRetuningIdParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
