// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GameCountByUser(ctx context.Context, userID int64) (int64, error)
	GameCreate(ctx context.Context, arg GameCreateParams) (Game, error)
	GameGetById(ctx context.Context, id string) (Game, error)
	GameGetByIdWithOrganizer(ctx context.Context, id string) (GameGetByIdWithOrganizerRow, error)
	GameGetPublicInfoById(ctx context.Context, id string) (GameGetPublicInfoByIdRow, error)
	GameListByUser(ctx context.Context, arg GameListByUserParams) ([]GameListByUserRow, error)
	GameUpdate(ctx context.Context, arg GameUpdateParams) error
	ListDemoUsers(ctx context.Context) ([]ListDemoUsersRow, error)
	ParticipantsList(ctx context.Context, arg ParticipantsListParams) ([]ParticipantsListRow, error)
	ParticipantsUpsert(ctx context.Context, arg ParticipantsUpsertParams) error
	UserGetById(ctx context.Context, id int64) (UserGetByIdRow, error)
	UserUpsertRetuningId(ctx context.Context, arg UserUpsertRetuningIdParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
