// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const listDemoUsers = `-- name: ListDemoUsers :many
select users.id, users.name, users.email, users.photo, users.created_at, users.updated_at, users.is_demo
from users
where is_demo
`

type ListDemoUsersRow struct {
	User User
}

func (q *Queries) ListDemoUsers(ctx context.Context) ([]ListDemoUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listDemoUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDemoUsersRow
	for rows.Next() {
		var i ListDemoUsersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Name,
			&i.User.Email,
			&i.User.Photo,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.IsDemo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userGetById = `-- name: UserGetById :one
select users.id, users.name, users.email, users.photo, users.created_at, users.updated_at, users.is_demo
from users
where id = ?
limit 1
`

type UserGetByIdRow struct {
	User User
}

func (q *Queries) UserGetById(ctx context.Context, id int64) (UserGetByIdRow, error) {
	row := q.db.QueryRowContext(ctx, userGetById, id)
	var i UserGetByIdRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Name,
		&i.User.Email,
		&i.User.Photo,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.IsDemo,
	)
	return i, err
}

const userUpsertRetuningId = `-- name: UserUpsertRetuningId :one
insert into users(
    name,
    email,
    photo,
    is_demo,
    updated_at
) values (?, ?, ?, ?, current_timestamp)
on conflict(email) do update set
    name = excluded.name,
    photo = coalesce(excluded.photo, users.photo), -- only update the photo if the new value is not null
    updated_at = excluded.updated_at
returning id
`

type UserUpsertRetuningIdParams struct {
	Name   sql.NullString
	Email  string
	Photo  sql.NullString
	IsDemo bool
}

func (q *Queries) UserUpsertRetuningId(ctx context.Context, arg UserUpsertRetuningIdParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, userUpsertRetuningId,
		arg.Name,
		arg.Email,
		arg.Photo,
		arg.IsDemo,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
