// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const userGetById = `-- name: UserGetById :one
select id, name, email, photo, created_at, updated_at
from users
where id = ?
limit 1
`

func (q *Queries) UserGetById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, userGetById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Photo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userUpsertRetuningId = `-- name: UserUpsertRetuningId :one
insert into users(
    name,
    email,
    photo,
    updated_at
) values (?, ?, ?, current_timestamp)
on conflict(email) do update set
    name = excluded.name,
    photo = coalesce(excluded.photo, users.photo), -- only update the photo if the new value is not null
    updated_at = excluded.updated_at
returning id
`

type UserUpsertRetuningIdParams struct {
	Name  sql.NullString
	Email string
	Photo sql.NullString
}

func (q *Queries) UserUpsertRetuningId(ctx context.Context, arg UserUpsertRetuningIdParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, userUpsertRetuningId, arg.Name, arg.Email, arg.Photo)
	var id int64
	err := row.Scan(&id)
	return id, err
}
