//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ParticipationStatus1.
const (
	Waitlisted ParticipationStatus1 = "waitlisted"
)

// Defines values for ParticipationStatusUpdate.
const (
	Going    ParticipationStatusUpdate = "going"
	NotGoing ParticipationStatusUpdate = "not_going"
)

// Defines values for UpdateGameParticipationRequestConfirmed.
const (
	True UpdateGameParticipationRequestConfirmed = true
)

// Defines values for GetApiAuthProviderCallbackParamsProvider.
const (
	GetApiAuthProviderCallbackParamsProviderGoogle GetApiAuthProviderCallbackParamsProvider = "google"
)

// Defines values for GetApiAuthProviderLoginParamsProvider.
const (
	GetApiAuthProviderLoginParamsProviderGoogle GetApiAuthProviderLoginParamsProvider = "google"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// ExpiresIn Token expiration time in seconds
	ExpiresIn *int `json:"expiresIn,omitempty"`

	// RefreshToken Optional refresh token for obtaining new access tokens
	RefreshToken *string `json:"refreshToken,omitempty"`

	// Token JWT or session token for authenticating subsequent requests
	Token string `json:"token"`
	User  User   `json:"user"`
}

// CreateGameRequest defines model for CreateGameRequest.
type CreateGameRequest struct {
	// Description Description of the game
	Description *string `json:"description,omitempty"`

	// DurationMinutes Duration of the game in minutes
	DurationMinutes *int64 `json:"durationMinutes,omitempty"`

	// GameSpotsLeft Number of spots left in the game, excluding the waitlist
	GameSpotsLeft *int64 `json:"gameSpotsLeft,omitempty"`

	// Location Location where the game will be held
	Location *string `json:"location,omitempty"`

	// MaxGuestsPerPlayer Maximum guests per player (0 to disable)
	MaxGuestsPerPlayer *int64 `json:"maxGuestsPerPlayer,omitempty"`

	// MaxPlayers Maximum number of players (must be at least 1)
	MaxPlayers *int64 `json:"maxPlayers,omitempty"`

	// Name Name of the game
	Name string `json:"name"`

	// StartsAt When the game starts
	StartsAt *time.Time `json:"startsAt,omitempty"`

	// TotalPriceCents Total price in cents
	TotalPriceCents *int64 `json:"totalPriceCents,omitempty"`
}

// Error Error message string
type Error = string

// Game defines model for Game.
type Game struct {
	// CreatedAt Timestamp when game was created
	CreatedAt time.Time `json:"createdAt"`

	// Description Description of the game
	Description *string `json:"description,omitempty"`

	// DurationMinutes Duration of the game in minutes
	DurationMinutes *int64 `json:"durationMinutes,omitempty"`

	// GameSpotsLeft Number of spots left in the game, excluding the waitlist
	GameSpotsLeft *int64 `json:"gameSpotsLeft,omitempty"`

	// Id Unique game identifier
	Id string `json:"id"`

	// Location Location where the game will be held
	Location *string `json:"location,omitempty"`

	// MaxGuestsPerPlayer Maximum guests per player (0 to disable)
	MaxGuestsPerPlayer *int64 `json:"maxGuestsPerPlayer,omitempty"`

	// MaxPlayers Maximum number of players (must be at least 1)
	MaxPlayers *int64 `json:"maxPlayers,omitempty"`

	// Name Name of the game
	Name string `json:"name"`

	// OrganizerId ID of the user who organized the game
	OrganizerId int `json:"organizerId"`

	// PublishedAt When the game is published (visible to others)
	PublishedAt *time.Time `json:"publishedAt,omitempty"`

	// StartsAt When the game starts
	StartsAt *time.Time `json:"startsAt,omitempty"`

	// TotalPriceCents Total price in cents
	TotalPriceCents *int64 `json:"totalPriceCents,omitempty"`

	// UpdatedAt Timestamp when game was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// GameDetail defines model for GameDetail.
type GameDetail struct {
	Game      Game `json:"game"`
	Organizer User `json:"organizer"`
}

// GameFields defines model for GameFields.
type GameFields struct {
	// Description Description of the game
	Description *string `json:"description,omitempty"`

	// DurationMinutes Duration of the game in minutes
	DurationMinutes *int64 `json:"durationMinutes,omitempty"`

	// GameSpotsLeft Number of spots left in the game, excluding the waitlist
	GameSpotsLeft *int64 `json:"gameSpotsLeft,omitempty"`

	// Location Location where the game will be held
	Location *string `json:"location,omitempty"`

	// MaxGuestsPerPlayer Maximum guests per player (0 to disable)
	MaxGuestsPerPlayer *int64 `json:"maxGuestsPerPlayer,omitempty"`

	// MaxPlayers Maximum number of players (must be at least 1)
	MaxPlayers *int64 `json:"maxPlayers,omitempty"`

	// Name Name of the game
	Name *string `json:"name,omitempty"`

	// StartsAt When the game starts
	StartsAt *time.Time `json:"startsAt,omitempty"`

	// TotalPriceCents Total price in cents
	TotalPriceCents *int64 `json:"totalPriceCents,omitempty"`
}

// GameListItem defines model for GameListItem.
type GameListItem struct {
	// Id Unique game identifier
	Id string `json:"id"`

	// IsOrganizer Whether the authenticated user is the organizer of this game
	IsOrganizer bool `json:"isOrganizer"`

	// Location Location where the game will be held
	Location *string `json:"location,omitempty"`

	// Name Name of the game
	Name      string `json:"name"`
	Organizer User   `json:"organizer"`

	// PublishedAt When the game is published (visible to others)
	PublishedAt nullable.Nullable[time.Time] `json:"publishedAt,omitempty"`

	// StartsAt When the game starts
	StartsAt nullable.Nullable[time.Time] `json:"startsAt,omitempty"`

	// UpdatedAt Timestamp when game was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// GameListResponse defines model for GameListResponse.
type GameListResponse struct {
	// Items Array of games for the current page
	Items []GameListItem `json:"items"`

	// Page Current page number (1-based)
	Page int `json:"page"`

	// PageSize Number of items per page
	PageSize int `json:"pageSize"`

	// Total Total number of items
	Total int `json:"total"`
}

// GameParticipation defines model for GameParticipation.
type GameParticipation struct {
	// CreatedAt Timestamp when the participation record was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// GameId Identifier of the game
	GameId string `json:"gameId"`

	// Status Participation status of the authenticated user
	Status ParticipationStatus `json:"status"`

	// UpdatedAt Timestamp when the participation record was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// UserId Identifier of the participant
	UserId string `json:"userId"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// Page Current page number (1-based)
	Page int `json:"page"`

	// PageSize Number of items per page
	PageSize int `json:"pageSize"`

	// Total Total number of items
	Total int `json:"total"`
}

// ParticipantWithUser defines model for ParticipantWithUser.
type ParticipantWithUser struct {
	// CreatedAt Timestamp when the participation record was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Guests Number of guests the participant is bringing
	Guests int `json:"guests"`

	// Status Participation status of the authenticated user
	Status ParticipationStatus `json:"status"`

	// UpdatedAt Timestamp when the participation record was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	User      User       `json:"user"`
}

// ParticipationStatus Participation status of the authenticated user
type ParticipationStatus struct {
	union json.RawMessage
}

// ParticipationStatus1 defines model for ParticipationStatus.1.
type ParticipationStatus1 string

// ParticipationStatusUpdate Allowed participation statuses that a user can set directly
type ParticipationStatusUpdate string

// PublicGameDetail defines model for PublicGameDetail.
type PublicGameDetail struct {
	union json.RawMessage
}

// PublicGameDetail0 Published game with available spots and start time
type PublicGameDetail0 struct {
	// GameSpotsLeft Number of spots left in the game
	GameSpotsLeft int64 `json:"gameSpotsLeft"`

	// Id Unique game identifier
	Id string `json:"id"`

	// Name Name of the game
	Name      string `json:"name"`
	Organizer struct {
		// Name Organizer's full name
		Name string `json:"name"`

		// Picture URL to organizer's profile picture
		Picture *string `json:"picture,omitempty"`
	} `json:"organizer"`

	// StartsAt When the game starts
	StartsAt time.Time `json:"startsAt"`
}

// PublicGameDetail1 Unpublished game with scheduled publish time
type PublicGameDetail1 struct {
	// Id Unique game identifier
	Id string `json:"id"`

	// Name Name of the game
	Name      string `json:"name"`
	Organizer struct {
		// Name Organizer's full name
		Name string `json:"name"`

		// Picture URL to organizer's profile picture
		Picture *string `json:"picture,omitempty"`
	} `json:"organizer"`

	// PublishedAt When the game will be published
	PublishedAt time.Time `json:"publishedAt"`
}

// UpdateGameParticipationRequest defines model for UpdateGameParticipationRequest.
type UpdateGameParticipationRequest struct {
	// Confirmed If the participant has confirmed (can only be set to false by the server when important details are changed on the game)
	Confirmed *UpdateGameParticipationRequestConfirmed `json:"confirmed,omitempty"`

	// Guests Number of guests the participant is bringing
	Guests *int `json:"guests,omitempty"`

	// Status Allowed participation statuses that a user can set directly
	Status ParticipationStatusUpdate `json:"status"`
}

// UpdateGameParticipationRequestConfirmed If the participant has confirmed (can only be set to false by the server when important details are changed on the game)
type UpdateGameParticipationRequestConfirmed bool

// UpdateGameRequest defines model for UpdateGameRequest.
type UpdateGameRequest struct {
	// Description Description of the game
	Description *string `json:"description,omitempty"`

	// DurationMinutes Duration of the game in minutes
	DurationMinutes *int64 `json:"durationMinutes,omitempty"`

	// GameSpotsLeft Number of spots left in the game, excluding the waitlist
	GameSpotsLeft *int64 `json:"gameSpotsLeft,omitempty"`

	// Location Location where the game will be held
	Location *string `json:"location,omitempty"`

	// MaxGuestsPerPlayer Maximum guests per player (0 to disable)
	MaxGuestsPerPlayer *int64 `json:"maxGuestsPerPlayer,omitempty"`

	// MaxPlayers Maximum number of players (must be at least 1)
	MaxPlayers *int64 `json:"maxPlayers,omitempty"`

	// Name Name of the game
	Name *string `json:"name,omitempty"`

	// PublishedAt When the game should become publicly visible. Past timestamps publish immediately. While in the future, it can be rescheduled or cleared.
	PublishedAt nullable.Nullable[time.Time] `json:"publishedAt,omitempty"`

	// StartsAt When the game starts
	StartsAt *time.Time `json:"startsAt,omitempty"`

	// TotalPriceCents Total price in cents
	TotalPriceCents *int64 `json:"totalPriceCents,omitempty"`
}

// User defines model for User.
type User struct {
	// CreatedAt Timestamp when user was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Email User's email address
	Email openapi_types.Email `json:"email"`

	// Id Unique user identifier
	Id string `json:"id"`

	// IsDemo Whether the user is a demo user
	IsDemo bool `json:"isDemo"`

	// Name User's full name
	Name *string `json:"name,omitempty"`

	// Picture URL to user's profile picture
	Picture *string `json:"picture,omitempty"`

	// UpdatedAt Timestamp when user was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// GetApiAuthProviderCallbackParams defines parameters for GetApiAuthProviderCallback.
type GetApiAuthProviderCallbackParams struct {
	// Code Authorization code returned by the provider on success
	Code *string `form:"code,omitempty" json:"code,omitempty"`

	// State State parameter for CSRF protection
	State *string `form:"state,omitempty" json:"state,omitempty"`

	// Error Error code if authorization failed
	Error *string `form:"error,omitempty" json:"error,omitempty"`

	// ErrorDescription Human-readable error description
	ErrorDescription *string `form:"error_description,omitempty" json:"error_description,omitempty"`
}

// GetApiAuthProviderCallbackParamsProvider defines parameters for GetApiAuthProviderCallback.
type GetApiAuthProviderCallbackParamsProvider string

// GetApiAuthProviderLoginParamsProvider defines parameters for GetApiAuthProviderLogin.
type GetApiAuthProviderLoginParamsProvider string

// GetApiGamesParams defines parameters for GetApiGames.
type GetApiGamesParams struct {
	// Page Page number (1-based) for pagination
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of games per page (max 25)
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PostApiGamesJSONRequestBody defines body for PostApiGames for application/json ContentType.
type PostApiGamesJSONRequestBody = CreateGameRequest

// PatchApiGamesIdJSONRequestBody defines body for PatchApiGamesId for application/json ContentType.
type PatchApiGamesIdJSONRequestBody = UpdateGameRequest

// PutApiGamesIdParticipantsJSONRequestBody defines body for PutApiGamesIdParticipants for application/json ContentType.
type PutApiGamesIdParticipantsJSONRequestBody = UpdateGameParticipationRequest

// AsParticipationStatusUpdate returns the union data inside the ParticipationStatus as a ParticipationStatusUpdate
func (t ParticipationStatus) AsParticipationStatusUpdate() (ParticipationStatusUpdate, error) {
	var body ParticipationStatusUpdate
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromParticipationStatusUpdate overwrites any union data inside the ParticipationStatus as the provided ParticipationStatusUpdate
func (t *ParticipationStatus) FromParticipationStatusUpdate(v ParticipationStatusUpdate) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeParticipationStatusUpdate performs a merge with any union data inside the ParticipationStatus, using the provided ParticipationStatusUpdate
func (t *ParticipationStatus) MergeParticipationStatusUpdate(v ParticipationStatusUpdate) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsParticipationStatus1 returns the union data inside the ParticipationStatus as a ParticipationStatus1
func (t ParticipationStatus) AsParticipationStatus1() (ParticipationStatus1, error) {
	var body ParticipationStatus1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromParticipationStatus1 overwrites any union data inside the ParticipationStatus as the provided ParticipationStatus1
func (t *ParticipationStatus) FromParticipationStatus1(v ParticipationStatus1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeParticipationStatus1 performs a merge with any union data inside the ParticipationStatus, using the provided ParticipationStatus1
func (t *ParticipationStatus) MergeParticipationStatus1(v ParticipationStatus1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ParticipationStatus) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ParticipationStatus) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPublicGameDetail0 returns the union data inside the PublicGameDetail as a PublicGameDetail0
func (t PublicGameDetail) AsPublicGameDetail0() (PublicGameDetail0, error) {
	var body PublicGameDetail0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPublicGameDetail0 overwrites any union data inside the PublicGameDetail as the provided PublicGameDetail0
func (t *PublicGameDetail) FromPublicGameDetail0(v PublicGameDetail0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePublicGameDetail0 performs a merge with any union data inside the PublicGameDetail, using the provided PublicGameDetail0
func (t *PublicGameDetail) MergePublicGameDetail0(v PublicGameDetail0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPublicGameDetail1 returns the union data inside the PublicGameDetail as a PublicGameDetail1
func (t PublicGameDetail) AsPublicGameDetail1() (PublicGameDetail1, error) {
	var body PublicGameDetail1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPublicGameDetail1 overwrites any union data inside the PublicGameDetail as the provided PublicGameDetail1
func (t *PublicGameDetail) FromPublicGameDetail1(v PublicGameDetail1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePublicGameDetail1 performs a merge with any union data inside the PublicGameDetail, using the provided PublicGameDetail1
func (t *PublicGameDetail) MergePublicGameDetail1(v PublicGameDetail1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PublicGameDetail) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PublicGameDetail) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Logout the authenticated user
	// (POST /api/auth/logout)
	PostApiAuthLogout(w http.ResponseWriter, r *http.Request)
	// Get authenticated user
	// (GET /api/auth/me)
	GetApiAuthMe(w http.ResponseWriter, r *http.Request)
	// OAuth callback endpoint
	// (GET /api/auth/{provider}/callback)
	GetApiAuthProviderCallback(w http.ResponseWriter, r *http.Request, provider GetApiAuthProviderCallbackParamsProvider, params GetApiAuthProviderCallbackParams)
	// Initiate OAuth login with a provider
	// (GET /api/auth/{provider}/login)
	GetApiAuthProviderLogin(w http.ResponseWriter, r *http.Request, provider GetApiAuthProviderLoginParamsProvider)
	// List demo users
	// (GET /api/demo/users)
	GetApiDemoUsers(w http.ResponseWriter, r *http.Request)
	// Impersonate a demo user
	// (POST /api/demo/users/{userId}/impersonate)
	PostApiDemoUsersUserIdImpersonate(w http.ResponseWriter, r *http.Request, userId string)
	// List user's games
	// (GET /api/games)
	GetApiGames(w http.ResponseWriter, r *http.Request, params GetApiGamesParams)
	// Create a new game
	// (POST /api/games)
	PostApiGames(w http.ResponseWriter, r *http.Request)
	// Get a game by ID
	// (GET /api/games/{id})
	GetApiGamesId(w http.ResponseWriter, r *http.Request, id string)
	// Update a game
	// (PATCH /api/games/{id})
	PatchApiGamesId(w http.ResponseWriter, r *http.Request, id string)
	// List game participants
	// (GET /api/games/{id}/participants)
	GetApiGamesIdParticipants(w http.ResponseWriter, r *http.Request, id string)
	// Set participation status
	// (PUT /api/games/{id}/participants)
	PutApiGamesIdParticipants(w http.ResponseWriter, r *http.Request, id string)
	// Get public game information
	// (GET /public/api/games/{id})
	GetPublicApiGamesId(w http.ResponseWriter, r *http.Request, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostApiAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostApiAuthLogout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetApiAuthMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAuthProviderCallback operation middleware
func (siw *ServerInterfaceWrapper) GetApiAuthProviderCallback(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "provider" -------------
	var provider GetApiAuthProviderCallbackParamsProvider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiAuthProviderCallbackParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameter("form", true, false, "code", r.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameter("form", true, false, "error", r.URL.Query(), &params.Error)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		return
	}

	// ------------- Optional query parameter "error_description" -------------

	err = runtime.BindQueryParameter("form", true, false, "error_description", r.URL.Query(), &params.ErrorDescription)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error_description", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAuthProviderCallback(w, r, provider, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAuthProviderLogin operation middleware
func (siw *ServerInterfaceWrapper) GetApiAuthProviderLogin(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "provider" -------------
	var provider GetApiAuthProviderLoginParamsProvider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAuthProviderLogin(w, r, provider)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiDemoUsers operation middleware
func (siw *ServerInterfaceWrapper) GetApiDemoUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiDemoUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiDemoUsersUserIdImpersonate operation middleware
func (siw *ServerInterfaceWrapper) PostApiDemoUsersUserIdImpersonate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiDemoUsersUserIdImpersonate(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiGames operation middleware
func (siw *ServerInterfaceWrapper) GetApiGames(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiGamesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiGames(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiGames operation middleware
func (siw *ServerInterfaceWrapper) PostApiGames(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiGames(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiGamesId operation middleware
func (siw *ServerInterfaceWrapper) GetApiGamesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiGamesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchApiGamesId operation middleware
func (siw *ServerInterfaceWrapper) PatchApiGamesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchApiGamesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiGamesIdParticipants operation middleware
func (siw *ServerInterfaceWrapper) GetApiGamesIdParticipants(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiGamesIdParticipants(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiGamesIdParticipants operation middleware
func (siw *ServerInterfaceWrapper) PutApiGamesIdParticipants(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiGamesIdParticipants(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicApiGamesId operation middleware
func (siw *ServerInterfaceWrapper) GetPublicApiGamesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicApiGamesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/auth/logout", wrapper.PostApiAuthLogout)
	m.HandleFunc("GET "+options.BaseURL+"/api/auth/me", wrapper.GetApiAuthMe)
	m.HandleFunc("GET "+options.BaseURL+"/api/auth/{provider}/callback", wrapper.GetApiAuthProviderCallback)
	m.HandleFunc("GET "+options.BaseURL+"/api/auth/{provider}/login", wrapper.GetApiAuthProviderLogin)
	m.HandleFunc("GET "+options.BaseURL+"/api/demo/users", wrapper.GetApiDemoUsers)
	m.HandleFunc("POST "+options.BaseURL+"/api/demo/users/{userId}/impersonate", wrapper.PostApiDemoUsersUserIdImpersonate)
	m.HandleFunc("GET "+options.BaseURL+"/api/games", wrapper.GetApiGames)
	m.HandleFunc("POST "+options.BaseURL+"/api/games", wrapper.PostApiGames)
	m.HandleFunc("GET "+options.BaseURL+"/api/games/{id}", wrapper.GetApiGamesId)
	m.HandleFunc("PATCH "+options.BaseURL+"/api/games/{id}", wrapper.PatchApiGamesId)
	m.HandleFunc("GET "+options.BaseURL+"/api/games/{id}/participants", wrapper.GetApiGamesIdParticipants)
	m.HandleFunc("PUT "+options.BaseURL+"/api/games/{id}/participants", wrapper.PutApiGamesIdParticipants)
	m.HandleFunc("GET "+options.BaseURL+"/public/api/games/{id}", wrapper.GetPublicApiGamesId)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xce28bNxL/Kry9A+oAiiU7SdHTX+fal1SB0xhx3BwQGC21O5LYcskNyZWtBvruhyG5",
	"u1wt9bBjJ3bRf1pL4nKG8/jNg7P5nKQyL6QAYXQy/JzodAY5tX8elWb2DnQhhQb8XChZgDIM7K9wXTAF",
	"eiTwQwY6VawwTIpkmLyXf4AgdgHFr4hhORAmiIZUikwnvQSuaV5wSIbPvh8MeolZFJAMEyYMTEEly16i",
	"YKJAz+xWXQpv7R+UE7+MGEtyIhWRY0OZYGJKBFwRmqagtfsZ6XpC2igmpkjHxAm8/vCeSEU0aG0PUG9P",
	"SzMDYVhKDdLQ5VjDpxKEIQr/r03rdAksXs/Gr1L2lr0eXfw5OviZjfRIvHuRHo++H/1R/O+X49f/3t/f",
	"j3FWalDI2L8UTJJh8s9+o6i+11L/Atcsrbg+lUxBlgw/+iP5DS7rneX4d0gN7nysgBp4RXN453hGMpTz",
	"t5Nk+HEzQXzoJQOe6WTZ+9wiK2gOEXKXy17yX6Wk6grZfk1y0JpOgfiTRySBRG/NYttqU3v07MhErJbl",
	"oA3NC3I1A0GmNAdyRTXxjyS9ZCJVTk0yTDJq4CkadYxblnX3vhDsUwluT5ah/UwYqJal0B/Tg9h2Uk2p",
	"YH+CGkX2HZ0QOSFmBgSVTa5mklTrM/s1UgzJHBw+e/4i5m9FOeZMz+Ki+YACqbYjTJN6NdmbM83GHIiR",
	"RJoZKP1kZ0mVRXZTZXCqDfHP7UhnxTsYPhcKtRcYRchTb5NFo5GdgKGMd5Fx6s11m5G2tHsrT/fabTaJ",
	"eXvgDx1WW0Jf1cFJ86myslVzSkYik1KRueQcFmPKOXlK8L8c5sA1uQKeyhz+kfSSnF6fgpiaWTI8GASY",
	"35hDVrpw8YaJ0kT4S078gpAbDCu5f6Bl54PAOpgw3z9PYmaPW5wX0uhTmETM8OcyH4NCehoXEQ4TgxQr",
	"6j0C1ykvMwwF+N0VZYYzbVqsxDjJmWB5mSfDaPDjMqVxnZz6X9AtFDRSuGKckzGQGfCspaCDw2fkDWWC",
	"nJseOZFXwsgrEXPGnF6/svHrDNQZpwuIAPYbeo1ck6ldSApQpLBLyd4AASBjmo45PAk5OLzx6XN67RjQ",
	"6zkQtWIcA5rs5aU2KAJqCAeEiYMnbYvYxMhBjBHhHXnFJlDe6/zhvBQZXZA3UtkU5JfaLzoeYInXnyMK",
	"0YYqo7fDsVu3M+gaaSg/UyyF4yrnW83eDOWkwBVo6qldFQryxWAX31qugaJTps3IQN4FozsOnEy/DcG1",
	"I0IMVlaKQUoHmQukTNtfamB1+ma6o3CjSqhpj6XkQMW38uA7Ntf1mchuseqr5BSi5BwhZ0UTd+1FW8l8",
	"u1RGOJ2G1h6qKmTtcoNLhoXebnn2GZ0y4Yy8m2czA3kEW46Uogu0RpSCtgUVaiAtlcISqqBTe5bq4W0Z",
	"VI0lDdhQpNCVlN1xfSp3RpVhKStqn71t1YCnKcLNiIJUquxWlQQKKZr110C44tgx6zflVlG2Tn/uHrmR",
	"TW889S3s3NWuux29pivMVofx4qi3r0Uc84zAvjsGYQ21w9xxYMZVhrJ38HRMNWTtXCRagdEpnLM/YVMW",
	"au3Y5V3OVVpZZndPG+zXhXjR3jbc7flhNKC3uwy4tWM7CbiPi7LW0QdmZhe+s/EwnMw1bTYI3We7K8aG",
	"IWuMm7SaFoHsH7Xv3aocbblXUot2o0UEx+6ctLWIuN0rt+8mbRj2BOwUuDq0L6yIbBwDgfXAx6Qq5SBE",
	"h0pIl/Ej+G26YY9zeQXZip7cgQAtixpCXeaZUkE0GJIxBanhC/RKz9FUOlMT0vzq/r6MaO8M06i03Z9o",
	"5LIi4Drl8imomRE6p8zmOr7kpSJzyRHx9tJtdnxBAf2FhfIdlwxfNYNuyzFOus7pvtNkUnJOxCr913Im",
	"yImMOnLBUlOqyLYX705tbh3sXig5YRxI9UxIY2ZMoYf9vv9mP5V5n86poWr/92Ia4kqp2NYgvKardk8F",
	"74aUOUyS22Yc8BJhtGtwRcSPEG2ykqPXu1/j/vO3Bf+FLPgGBW9V7teP3K09h5zEyx4XqzrFT3AjtJKe",
	"STFhKodYUt7JxMkMM7HqCbKHUU0KvsATY3Qzkkwo10DGC/uoBjW39xcgCMsLqQxuktkApglVQNIZFVPI",
	"iGxk+KSJjViVX8b6MA8vu6tSjXjuFLOqRlNfel23UsTsbq16JkuekTGkMvc2m/IF8X2afXKGeaapEtO6",
	"l0NYnkPGqAG+2CcfZuiePvhPSnTSHmHGpjxjIAoayJSKpByogmz/li2ZZdzov7DycLdst6gyIPep2AqM",
	"aQtd9ldCs0yBbt8fI8H/BKgVEnR73uwG0nU34zHF3g3GO6knkMvNTdSqbUpJBrmsEvJ6c+vtMQeNRw0v",
	"l7sPGKW+71hxk9qtNqc76gVWFuEV1gUTBC5IS8XM4hwhwtn/GD1NHZVm1nx6WbHw+sN7zIfsalSd/bVh",
	"B6WVLHFjJiYRGzk6G7mxjALEdIH2a5ixcvbfkKOzUdJL5qC0e+Jgf7A/sLlGAYIWLBkmz+xXvaSgZmY5",
	"7tOC9bEE7HM5laULV1JHJH6MMKJXS8ZmpgPLGy6nmsjS1IacWOLusnGUYaEktTkqGIro1BFE6buOqWXo",
	"cPC8S/u8tNMnaMULJGLjV2kx/fngwAdVA8KybeDa9AtOmWjGcLaFFzdXYaW/6u14WKnsHMBTwsSccmZh",
	"NWda29tKOyQSGoQNJqEpfLxcXvYSXeY5VQt7czGthBStvg2dajTFo5ack0sk0ijMufsUIrp6B6ZUQoct",
	"Yb5YU+m31PMKKu28ga5mBiuSpkXBPXP937W8gbx916Mj7qMui49Ux6/AfIlyPxdKzlkGatlPKedjmv6x",
	"Vts/UZFxcNp+i9uS6uHvNFHgGiCETgwoB5RTRYXReMAMBANNqvM7VtYbxZnf97hiCZFE0RyMvWPutEXe",
	"dzhCTMVfEICqhHuYBL82UOyykUa3TfdGTjlEWjbdgvIoPBdJZYbJEboGZFXCXJHGfFg7mKl4/FSCWjRM",
	"4uNJyNBW8pin2mTYScjC9/H5u5dI1EDqhR2jhUnsDYm5GTB7RjZpa5RMKOM2HsZogfWLG9H6qcypeKqA",
	"Zra/ZXcg4ZINlH5tr1tP9fIe8ac1kRmBhFbAoVFQejY4jAGv9zasy5TlNHNdDBckpSKVuGdAMz+Zcbr2",
	"jvtltQdmXZF9sAiwQnZWpjcKdGmhdHCfUDry2OlHOBs+J0rmDQjcP6a30bVyAIvgNUQ7ZKrglYDICsnc",
	"5ddNMZrLqWN7TTh2VqGbBN/IOFy3/dZfCW2D41NL/cZY7NP4zjRu47/3gtKrfr3VkQLxuANEhbSTP/ni",
	"ZXfRPwhvqhWmC0ix3Fy15JFghmGscYey1ugvIcLIu9WsseLso33qrakl5bwpUPUaI8Xi6cL//kVYvtMg",
	"QzUtszLA0BHrKUNkmgTsY1agGMwhq3IAi/wOp57dp4rRKxF9ntpAQTUR0ri+PGQI7pbHHIO6lm5wqoIp",
	"wnQ1Jpjtr9iDPWFLO5XqXTkbUXj/s7vKX/ZZXoDSUvgLuHg1WNWcvuUU47iHn65mLEWM1Z2qkaHUC05T",
	"8BGyoesnU9sdkGgdWRvYhWV+FLC+BQ6bge+aCCIDa+0QAcF64GE9BH7NRGZdIdVKYIJDZYFMH6t1B1pe",
	"sZE1Vm5npHZCNDdNtX6WEZjt0/kLAiwNpQovo8WUsHUF1CvLxRazPItNvNgIXTRTNPHsuhOxMpjQkhs7",
	"JbNpPreb3wdNfSuQak6G7OX0mhy+eLKBBTu7EmdjYEd3HR+HL7YwdZ9e05nV2xAlnAQ2BYhH2IDCs/kO",
	"7tSbZeU7zkwvl711fUDbsNeE2tfC8Ol98j6YPvUNfUJtC1vRibGtQabdvVUwkdoeDC6FYZww055gnTPq",
	"kmbb0q3hYX9dQKiczBcgP8pscWdW033ba9luHmMgWN6z2fpZlIil4K+19LtW+lXrvowa+lidw6k5sO+I",
	"c7QiS/8zy5abwotFDnQHZIl7VxkvCDOajE42hQubaWwt6+x+dqNIwsIeTrKyg/1uwtnn92lKljqmJxNZ",
	"itX6yjZza7VZSUfgkpp0Fik5LXJpQgWBa6ZtjuBQ8y3iYRsEMZ32UGdmwJRf6cfLbHqhCVMK7C0P4qgU",
	"qXv3IRyOsVMDBdUasn0ympDfghvq3+wW7bvjNhM5XQR3yAjJ0nKWAq+oICd7pbATCLgPA549aSDcXW9r",
	"ApMJpIbNIYLXKK1vbOZ3HyK6EwYPL0T429G/Q0Q7RNx7MfRSqjHLMhDkqQWaeiakGTf6NjC3a2B0xu2B",
	"cKeg2A8GgXYrwMIH6rda6rZXMBXo4BGPXpo1A8EuL/XTzpiZVottVVUNQEmVgWrT1WwqsOgryJ4dD35i",
	"M1hcnNPrX6v3JDnLWSQRbUXvs/D8jyyS79Rzi72QcIMWXEvsD7/GetDuaWVqDahoW10kVSk3FHZS+RCx",
	"rhHynY662xp3jYT+8iF5yH0mAdGB0G+QEbTfyovYXfQFkb8ThccHAudgos65Jly7AdSbl7I29lUT+Slh",
	"wg3aIT06lmVVLdniI/pqcs8PYujwdZb2GzL2YRTDAs/UfdDNOJvuAHg0Jru3ef6adXXnTaWYhztN+X/p",
	"o1HXwy24izjHMUu2HqLmcU2eypRyksEcuCxyEMYPySe9pFTcT14O+32O62ZSm+EPgx8GyfJy+f8AAAD/",
	"/3Q02v7TSwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
