//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ParticipationStatus1.
const (
	Waitlisted ParticipationStatus1 = "waitlisted"
)

// Defines values for ParticipationStatusUpdate.
const (
	Going    ParticipationStatusUpdate = "going"
	NotGoing ParticipationStatusUpdate = "not_going"
)

// Defines values for UpdateGameParticipationRequestConfirmed.
const (
	True UpdateGameParticipationRequestConfirmed = true
)

// Defines values for GetApiAuthProviderCallbackParamsProvider.
const (
	GetApiAuthProviderCallbackParamsProviderGoogle GetApiAuthProviderCallbackParamsProvider = "google"
)

// Defines values for GetApiAuthProviderLoginParamsProvider.
const (
	GetApiAuthProviderLoginParamsProviderGoogle GetApiAuthProviderLoginParamsProvider = "google"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// ExpiresIn Token expiration time in seconds
	ExpiresIn *int `json:"expiresIn,omitempty"`

	// RefreshToken Optional refresh token for obtaining new access tokens
	RefreshToken *string `json:"refreshToken,omitempty"`

	// Token JWT or session token for authenticating subsequent requests
	Token string `json:"token"`
	User  User   `json:"user"`
}

// CreateGameRequest defines model for CreateGameRequest.
type CreateGameRequest struct {
	// Description Description of the game
	Description *string `json:"description,omitempty"`

	// DurationMinutes Duration of the game in minutes
	DurationMinutes *int64 `json:"durationMinutes,omitempty"`

	// GameSpotsLeft Number of spots left in the game, excluding the waitlist
	GameSpotsLeft *int64 `json:"gameSpotsLeft,omitempty"`

	// Location Location where the game will be held
	Location *string `json:"location,omitempty"`

	// MaxGuestsPerPlayer Maximum guests per player (0 to disable)
	MaxGuestsPerPlayer *int64 `json:"maxGuestsPerPlayer,omitempty"`

	// MaxPlayers Maximum number of players (must be at least 1)
	MaxPlayers *int64 `json:"maxPlayers,omitempty"`

	// Name Name of the game
	Name string `json:"name"`

	// StartsAt When the game starts
	StartsAt *time.Time `json:"startsAt,omitempty"`

	// TotalPriceCents Total price in cents
	TotalPriceCents *int64 `json:"totalPriceCents,omitempty"`
}

// Error Error message string
type Error = string

// Game defines model for Game.
type Game struct {
	// CreatedAt Timestamp when game was created
	CreatedAt time.Time `json:"createdAt"`

	// Description Description of the game
	Description *string `json:"description,omitempty"`

	// DurationMinutes Duration of the game in minutes
	DurationMinutes *int64 `json:"durationMinutes,omitempty"`

	// GameSpotsLeft Number of spots left in the game, excluding the waitlist
	GameSpotsLeft *int64 `json:"gameSpotsLeft,omitempty"`

	// Id Unique game identifier
	Id string `json:"id"`

	// Location Location where the game will be held
	Location *string `json:"location,omitempty"`

	// MaxGuestsPerPlayer Maximum guests per player (0 to disable)
	MaxGuestsPerPlayer *int64 `json:"maxGuestsPerPlayer,omitempty"`

	// MaxPlayers Maximum number of players (must be at least 1)
	MaxPlayers *int64 `json:"maxPlayers,omitempty"`

	// Name Name of the game
	Name string `json:"name"`

	// OrganizerId ID of the user who organized the game
	OrganizerId int `json:"organizerId"`

	// PublishedAt When the game is published (visible to others)
	PublishedAt *time.Time `json:"publishedAt,omitempty"`

	// StartsAt When the game starts
	StartsAt *time.Time `json:"startsAt,omitempty"`

	// TotalPriceCents Total price in cents
	TotalPriceCents *int64 `json:"totalPriceCents,omitempty"`

	// UpdatedAt Timestamp when game was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// GameDetail defines model for GameDetail.
type GameDetail struct {
	Game      Game `json:"game"`
	Organizer User `json:"organizer"`
}

// GameFields defines model for GameFields.
type GameFields struct {
	// Description Description of the game
	Description *string `json:"description,omitempty"`

	// DurationMinutes Duration of the game in minutes
	DurationMinutes *int64 `json:"durationMinutes,omitempty"`

	// GameSpotsLeft Number of spots left in the game, excluding the waitlist
	GameSpotsLeft *int64 `json:"gameSpotsLeft,omitempty"`

	// Location Location where the game will be held
	Location *string `json:"location,omitempty"`

	// MaxGuestsPerPlayer Maximum guests per player (0 to disable)
	MaxGuestsPerPlayer *int64 `json:"maxGuestsPerPlayer,omitempty"`

	// MaxPlayers Maximum number of players (must be at least 1)
	MaxPlayers *int64 `json:"maxPlayers,omitempty"`

	// Name Name of the game
	Name *string `json:"name,omitempty"`

	// StartsAt When the game starts
	StartsAt *time.Time `json:"startsAt,omitempty"`

	// TotalPriceCents Total price in cents
	TotalPriceCents *int64 `json:"totalPriceCents,omitempty"`
}

// GameListItem defines model for GameListItem.
type GameListItem struct {
	// Id Unique game identifier
	Id string `json:"id"`

	// IsOrganizer Whether the authenticated user is the organizer of this game
	IsOrganizer bool `json:"isOrganizer"`

	// Location Location where the game will be held
	Location *string `json:"location,omitempty"`

	// Name Name of the game
	Name      string `json:"name"`
	Organizer User   `json:"organizer"`

	// PublishedAt When the game is published (visible to others)
	PublishedAt nullable.Nullable[time.Time] `json:"publishedAt,omitempty"`

	// StartsAt When the game starts
	StartsAt nullable.Nullable[time.Time] `json:"startsAt,omitempty"`

	// UpdatedAt Timestamp when game was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// GameListResponse defines model for GameListResponse.
type GameListResponse struct {
	// Items Array of games for the current page
	Items []GameListItem `json:"items"`

	// Page Current page number (1-based)
	Page int `json:"page"`

	// PageSize Number of items per page
	PageSize int `json:"pageSize"`

	// Total Total number of items
	Total int `json:"total"`
}

// GameParticipation defines model for GameParticipation.
type GameParticipation struct {
	// CreatedAt Timestamp when the participation record was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// GameId Identifier of the game
	GameId string `json:"gameId"`

	// Status Participation status of the authenticated user
	Status ParticipationStatus `json:"status"`

	// UpdatedAt Timestamp when the participation record was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// UserId Identifier of the participant
	UserId string `json:"userId"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// Page Current page number (1-based)
	Page int `json:"page"`

	// PageSize Number of items per page
	PageSize int `json:"pageSize"`

	// Total Total number of items
	Total int `json:"total"`
}

// ParticipantWithUser defines model for ParticipantWithUser.
type ParticipantWithUser struct {
	// CreatedAt Timestamp when the participation record was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Guests Number of guests the participant is bringing
	Guests int `json:"guests"`

	// Status Participation status of the authenticated user
	Status ParticipationStatus `json:"status"`

	// UpdatedAt Timestamp when the participation record was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	User      User       `json:"user"`
}

// ParticipationStatus Participation status of the authenticated user
type ParticipationStatus struct {
	union json.RawMessage
}

// ParticipationStatus1 defines model for ParticipationStatus.1.
type ParticipationStatus1 string

// ParticipationStatusUpdate Allowed participation statuses that a user can set directly
type ParticipationStatusUpdate string

// UpdateGameParticipationRequest defines model for UpdateGameParticipationRequest.
type UpdateGameParticipationRequest struct {
	// Confirmed If the participant has confirmed (can only be set to false by the server when important details are changed on the game)
	Confirmed *UpdateGameParticipationRequestConfirmed `json:"confirmed,omitempty"`

	// Guests Number of guests the participant is bringing
	Guests *int `json:"guests,omitempty"`

	// Status Allowed participation statuses that a user can set directly
	Status ParticipationStatusUpdate `json:"status"`
}

// UpdateGameParticipationRequestConfirmed If the participant has confirmed (can only be set to false by the server when important details are changed on the game)
type UpdateGameParticipationRequestConfirmed bool

// UpdateGameRequest defines model for UpdateGameRequest.
type UpdateGameRequest struct {
	// Description Description of the game
	Description *string `json:"description,omitempty"`

	// DurationMinutes Duration of the game in minutes
	DurationMinutes *int64 `json:"durationMinutes,omitempty"`

	// GameSpotsLeft Number of spots left in the game, excluding the waitlist
	GameSpotsLeft *int64 `json:"gameSpotsLeft,omitempty"`

	// Location Location where the game will be held
	Location *string `json:"location,omitempty"`

	// MaxGuestsPerPlayer Maximum guests per player (0 to disable)
	MaxGuestsPerPlayer *int64 `json:"maxGuestsPerPlayer,omitempty"`

	// MaxPlayers Maximum number of players (must be at least 1)
	MaxPlayers *int64 `json:"maxPlayers,omitempty"`

	// Name Name of the game
	Name *string `json:"name,omitempty"`

	// PublishedAt When the game should become publicly visible. Past timestamps publish immediately. While in the future, it can be rescheduled or cleared.
	PublishedAt nullable.Nullable[time.Time] `json:"publishedAt,omitempty"`

	// StartsAt When the game starts
	StartsAt *time.Time `json:"startsAt,omitempty"`

	// TotalPriceCents Total price in cents
	TotalPriceCents *int64 `json:"totalPriceCents,omitempty"`
}

// User defines model for User.
type User struct {
	// CreatedAt Timestamp when user was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Email User's email address
	Email openapi_types.Email `json:"email"`

	// Id Unique user identifier
	Id string `json:"id"`

	// IsDemo Whether the user is a demo user
	IsDemo bool `json:"isDemo"`

	// Name User's full name
	Name *string `json:"name,omitempty"`

	// Picture URL to user's profile picture
	Picture *string `json:"picture,omitempty"`

	// UpdatedAt Timestamp when user was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// GetApiAuthProviderCallbackParams defines parameters for GetApiAuthProviderCallback.
type GetApiAuthProviderCallbackParams struct {
	// Code Authorization code returned by the provider on success
	Code *string `form:"code,omitempty" json:"code,omitempty"`

	// State State parameter for CSRF protection
	State *string `form:"state,omitempty" json:"state,omitempty"`

	// Error Error code if authorization failed
	Error *string `form:"error,omitempty" json:"error,omitempty"`

	// ErrorDescription Human-readable error description
	ErrorDescription *string `form:"error_description,omitempty" json:"error_description,omitempty"`
}

// GetApiAuthProviderCallbackParamsProvider defines parameters for GetApiAuthProviderCallback.
type GetApiAuthProviderCallbackParamsProvider string

// GetApiAuthProviderLoginParamsProvider defines parameters for GetApiAuthProviderLogin.
type GetApiAuthProviderLoginParamsProvider string

// GetApiGamesParams defines parameters for GetApiGames.
type GetApiGamesParams struct {
	// Page Page number (1-based) for pagination
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of games per page (max 25)
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PostApiGamesJSONRequestBody defines body for PostApiGames for application/json ContentType.
type PostApiGamesJSONRequestBody = CreateGameRequest

// PatchApiGamesIdJSONRequestBody defines body for PatchApiGamesId for application/json ContentType.
type PatchApiGamesIdJSONRequestBody = UpdateGameRequest

// PutApiGamesIdParticipantsJSONRequestBody defines body for PutApiGamesIdParticipants for application/json ContentType.
type PutApiGamesIdParticipantsJSONRequestBody = UpdateGameParticipationRequest

// AsParticipationStatusUpdate returns the union data inside the ParticipationStatus as a ParticipationStatusUpdate
func (t ParticipationStatus) AsParticipationStatusUpdate() (ParticipationStatusUpdate, error) {
	var body ParticipationStatusUpdate
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromParticipationStatusUpdate overwrites any union data inside the ParticipationStatus as the provided ParticipationStatusUpdate
func (t *ParticipationStatus) FromParticipationStatusUpdate(v ParticipationStatusUpdate) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeParticipationStatusUpdate performs a merge with any union data inside the ParticipationStatus, using the provided ParticipationStatusUpdate
func (t *ParticipationStatus) MergeParticipationStatusUpdate(v ParticipationStatusUpdate) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsParticipationStatus1 returns the union data inside the ParticipationStatus as a ParticipationStatus1
func (t ParticipationStatus) AsParticipationStatus1() (ParticipationStatus1, error) {
	var body ParticipationStatus1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromParticipationStatus1 overwrites any union data inside the ParticipationStatus as the provided ParticipationStatus1
func (t *ParticipationStatus) FromParticipationStatus1(v ParticipationStatus1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeParticipationStatus1 performs a merge with any union data inside the ParticipationStatus, using the provided ParticipationStatus1
func (t *ParticipationStatus) MergeParticipationStatus1(v ParticipationStatus1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ParticipationStatus) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ParticipationStatus) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Logout the authenticated user
	// (POST /api/auth/logout)
	PostApiAuthLogout(w http.ResponseWriter, r *http.Request)
	// Get authenticated user
	// (GET /api/auth/me)
	GetApiAuthMe(w http.ResponseWriter, r *http.Request)
	// OAuth callback endpoint
	// (GET /api/auth/{provider}/callback)
	GetApiAuthProviderCallback(w http.ResponseWriter, r *http.Request, provider GetApiAuthProviderCallbackParamsProvider, params GetApiAuthProviderCallbackParams)
	// Initiate OAuth login with a provider
	// (GET /api/auth/{provider}/login)
	GetApiAuthProviderLogin(w http.ResponseWriter, r *http.Request, provider GetApiAuthProviderLoginParamsProvider)
	// List demo users
	// (GET /api/demo/users)
	GetApiDemoUsers(w http.ResponseWriter, r *http.Request)
	// Impersonate a demo user
	// (POST /api/demo/users/{userId}/impersonate)
	PostApiDemoUsersUserIdImpersonate(w http.ResponseWriter, r *http.Request, userId string)
	// List user's games
	// (GET /api/games)
	GetApiGames(w http.ResponseWriter, r *http.Request, params GetApiGamesParams)
	// Create a new game
	// (POST /api/games)
	PostApiGames(w http.ResponseWriter, r *http.Request)
	// Get a game by ID
	// (GET /api/games/{id})
	GetApiGamesId(w http.ResponseWriter, r *http.Request, id string)
	// Update a game
	// (PATCH /api/games/{id})
	PatchApiGamesId(w http.ResponseWriter, r *http.Request, id string)
	// List game participants
	// (GET /api/games/{id}/participants)
	GetApiGamesIdParticipants(w http.ResponseWriter, r *http.Request, id string)
	// Set participation status
	// (PUT /api/games/{id}/participants)
	PutApiGamesIdParticipants(w http.ResponseWriter, r *http.Request, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostApiAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostApiAuthLogout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetApiAuthMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAuthProviderCallback operation middleware
func (siw *ServerInterfaceWrapper) GetApiAuthProviderCallback(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "provider" -------------
	var provider GetApiAuthProviderCallbackParamsProvider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiAuthProviderCallbackParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameter("form", true, false, "code", r.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameter("form", true, false, "error", r.URL.Query(), &params.Error)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		return
	}

	// ------------- Optional query parameter "error_description" -------------

	err = runtime.BindQueryParameter("form", true, false, "error_description", r.URL.Query(), &params.ErrorDescription)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error_description", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAuthProviderCallback(w, r, provider, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAuthProviderLogin operation middleware
func (siw *ServerInterfaceWrapper) GetApiAuthProviderLogin(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "provider" -------------
	var provider GetApiAuthProviderLoginParamsProvider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAuthProviderLogin(w, r, provider)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiDemoUsers operation middleware
func (siw *ServerInterfaceWrapper) GetApiDemoUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiDemoUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiDemoUsersUserIdImpersonate operation middleware
func (siw *ServerInterfaceWrapper) PostApiDemoUsersUserIdImpersonate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiDemoUsersUserIdImpersonate(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiGames operation middleware
func (siw *ServerInterfaceWrapper) GetApiGames(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiGamesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiGames(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiGames operation middleware
func (siw *ServerInterfaceWrapper) PostApiGames(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiGames(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiGamesId operation middleware
func (siw *ServerInterfaceWrapper) GetApiGamesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiGamesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchApiGamesId operation middleware
func (siw *ServerInterfaceWrapper) PatchApiGamesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchApiGamesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiGamesIdParticipants operation middleware
func (siw *ServerInterfaceWrapper) GetApiGamesIdParticipants(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiGamesIdParticipants(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiGamesIdParticipants operation middleware
func (siw *ServerInterfaceWrapper) PutApiGamesIdParticipants(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiGamesIdParticipants(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/auth/logout", wrapper.PostApiAuthLogout)
	m.HandleFunc("GET "+options.BaseURL+"/api/auth/me", wrapper.GetApiAuthMe)
	m.HandleFunc("GET "+options.BaseURL+"/api/auth/{provider}/callback", wrapper.GetApiAuthProviderCallback)
	m.HandleFunc("GET "+options.BaseURL+"/api/auth/{provider}/login", wrapper.GetApiAuthProviderLogin)
	m.HandleFunc("GET "+options.BaseURL+"/api/demo/users", wrapper.GetApiDemoUsers)
	m.HandleFunc("POST "+options.BaseURL+"/api/demo/users/{userId}/impersonate", wrapper.PostApiDemoUsersUserIdImpersonate)
	m.HandleFunc("GET "+options.BaseURL+"/api/games", wrapper.GetApiGames)
	m.HandleFunc("POST "+options.BaseURL+"/api/games", wrapper.PostApiGames)
	m.HandleFunc("GET "+options.BaseURL+"/api/games/{id}", wrapper.GetApiGamesId)
	m.HandleFunc("PATCH "+options.BaseURL+"/api/games/{id}", wrapper.PatchApiGamesId)
	m.HandleFunc("GET "+options.BaseURL+"/api/games/{id}/participants", wrapper.GetApiGamesIdParticipants)
	m.HandleFunc("PUT "+options.BaseURL+"/api/games/{id}/participants", wrapper.PutApiGamesIdParticipants)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbbW8bNxL+K7y9A2oDsiQ7SdHTp3PtS6rAaYw4bg4IjJbaHe2y5ZIbkmtbDfTfD0Ny",
	"37TUi524sYF+aSNplzOceeaZF9Kfo1jmhRQgjI4mnyMdZ5BT+8/j0mTvQBdSaMDPhZIFKMPA/gq3BVOg",
	"pwI/JKBjxQrDpIgm0Xv5BwhiH6D4FTEsB8IE0RBLkehoEMEtzQsO0eTZ9+PxIDKLAqJJxISBFFS0HEQK",
	"5gp0ZpfqS3hr/0E58Y8RY0XOpSJyZigTTKREwA2hcQxau59RrhekjWIiRTkmLOD1h/dEKqJBa7uBenla",
	"mgyEYTE1KEOXMw2fShCGKPy/Np3dRbB4nc1exewtez29/HN6+DOb6ql49yI+mX4//aP43y8nr/89HA5D",
	"mpUaFCr2LwXzaBL9c9Q4auS9NLrEZ5bWXJ9KpiCJJh/9lvwCV/XKcvY7xAZXPlFADbyiObxzOqMYyvnb",
	"eTT5uFkgvvSSAU90tBx87ogVNIeAuKvlIPqvUlL1jWy/JjloTVMgfucBS6DQe6vYRW1st54cmwBqWQ7a",
	"0LwgNxkIktIcyA3VxL8SDaK5VDk10SRKqIEDBHVIW5b0174U7FMJbk2WIH7mDFQHKfTH+DC0nFQpFexP",
	"UNPAutNTIufEZEDQ2eQmk6R6PrFfo8S2mMOjZ89fhOKtKGec6Sxsmg9okGo5wjSpnyZ710yzGQdiJJEm",
	"A6X3d7ZUWSR3dQan2hD/3o5yVqKD4Xttow5aoGjrNNiEaATZKRjKeJ8ZUw/XbSDtePdeke692ywSivZW",
	"PPRU7Rh91QenzacKZatwiqYikVKRa8k5LGaUc3JA8L8croFrcgM8ljn8IxpEOb09A5GaLJocjluc38Ah",
	"KV26eMNEaQL6Raf+gbY2mFZy/0IH5+MWOpgw3z+PQrDHJS4KafQZzAMw/LnMZ6BQnsaHCIe5QYmV9AGB",
	"25iXCaYC/O6GMsOZNh1VQprkTLC8zKNJMPlxGdOwT878LxgWChor3DDOyQxIBjzpOOjw6Bl5Q5kgF2ZA",
	"TuWNMPJGhIIxp7evbP46B3XO6QIChP2G3qLWJLUPkgIUKeyjZG+MBJAwTWcc9tsaHN159zm9dQro9RqI",
	"2jFOAU328lIbNAE1hAPSxOF+FxGbFDkMKSJ8IK9gAu29Lh4uSpHQBXkjlS1BfqnjohcBVnj9OeAQbagy",
	"ejsdu+d2Jl0jDeXnisVwUtV8q9WboZwU+ARCPbZPtQ35YrxLbC3XUNEZ02ZqIO+T0VdOnEy/bZNrz4SY",
	"rKwVWyUdJC6RMm1/qYnV+ZvpnsONKqGWPZOSAxXfKoK/MlzXVyK75aq/pKYQJedIOSue+NpRtFXMtytl",
	"hPNpG+1tV7VVu9oQku1Gb7c6+5ymTDiQ9+tsZiAPcMuxUnSBaEQraNtQoQfiUilsoQqa2r1UL2+roGou",
	"aciGooS+peyK60u5c6oMi1lRx+x9uwbcTdFejCiIpUru1UmgkYJVf02EK4EdQr8pt5qys/sL98qdML1x",
	"1/fAuetdd9t6LVeYrQHjzVEvX5s4FBktfPcAYYHaU+6kBeOqQtk7PJhRDUm3Fgl2YDSFC/YnbKpCLY5d",
	"3eVCpVNl9te0yX5dihfdZdurPT8KJvTulAGXdmpHLe3Dpqx99IGZ7NJPNh5HkLmhzQaj+2p3BWyYsma4",
	"SGdo0bL9k469e7WjnfCKatNuRERr272ddh4ibvUq7PtFG6Y9ATslrp7sS2sim8dAYD/wMapaOWizQ2Wk",
	"q/AW/DL9tMe5vIFkxU9uQ4DIooZQV3nGVBANhiRMQWz4AqPSa5RKBzUhza/u31cB7zkdekmtNelbCTsp",
	"5kzlECLbHsOSDCOseoPsobZS8AUWrqi1kWROuQYyW9hXNahrO5cCQVheSGVwkcQOTjShCkicUZFCQmRT",
	"i+03e8Zq6ypUXz++qK0gFI6JUAw0nvrSMexKctq97NaZLHlCZhDLHFwFHvMF8fX3kJwjf5iKcOoanbA8",
	"h4RRA3wxJB8yxqGaisxLUyoYEGYslGdAFKDWScnRy4rEHKiCZHjPUnsZrOG+NKO46ek9sgfkfgS40rZq",
	"UN9pYn8lNEkU6O65AAr8j/84jGXeFujWvNtk2XWt4QbZznzDHfIp5HJzc1y1w5QkkMuKaOvFbbSHAjTc",
	"jHq7zEvOiVhtRl/LTJBTGbRzwWLEVWDFd2fIOqVbuFByjmCsHm8vnxlT6Mlo1LL6iF5TQ9Xw9yJtO6BU",
	"7MvG1TWcvlKPVyHCO6xPJkhcEJeKmcUFUoTD/wwjTR2XJms+vaxUeP3hfTRwx33WdfbXRh20VrTEhZmY",
	"BzByfD51x20FiHSB+DXMWDv7b8jx+TQaRNegtHvjcDgeju0coQBBCxZNomf2KyweTWY1HtGCjTC1j7hM",
	"ZenSldQBi58gjejVUqA5q6MiIVymmsjS1ECOrHA3RMbuIjqX2hwXDE105gSi9V0nbBU6Gj/vy74o7aki",
	"oniBQmz+Ki2nPx8f+qRqQFi1DdyaUcEpE83x6rb04s7LrPVXox03K5U93zkgTFxTziyt5kxrO4W2h39t",
	"QNhk0obCx6vl1SDSZZ5TtbATqbQyUrCqMjTVCMXjjp2jKxTSOMyFewoBX70DUyqh260+X6yp4DrueQWV",
	"d95A3zPjFUvTouBeudHvWt7B3r6a7Zn7uK/iE/XxKzBf4tzPhZLXLAG1HMWU8xmN/1jr7Z+oSDg4b7/F",
	"ZUn18neaKHCFLaFzA8oRZaqoMBo3mIBgoEm1f6fKelCc+3VPKpWQSRTNwdizg489lu5phJyKvyABVbO0",
	"SdT6taFiV400vm2qcplyCJTiWJj14VTvi8QyweIIQwOSqmCuRGM9rB3NVDp+KkEtGiXx9ait0FbxWKfa",
	"YthZyNL3ycW7lyjUQOyNHZKFRewdhbmzfbtHNu96lMwp4zYfhmSBjYs7yfqpzKk4UEATLByJXYG0H9kg",
	"6dfuc+ulXj0g/3Ru2gQooZNwaJCUno2PQsTrow37MmU1TcgNM9V9GalIZe4MaOJP3M7Wnl28rNbAqiuw",
	"DjYB1sgOZXqjQZeWSscPSaVTz53+ak6j51zJvCGBh+f0LrtWAWAZvKZox0wVvRIQSSGZG2relaO5TJ3a",
	"a9KxQ4VuCnwjw3TdjVs/6ttGx2dW+p252JfxvVtWTfw+CEuvxvXWQGqZx20gaKSd4sk3L7ub/lFEU+0w",
	"XUCM7eYqkqeCGYa5xm3KotHRBW1n3q2wxo5zhPjUW0tLynnToOo1IMXm6dL//kVcvtMBVXUKunIw1TPr",
	"GUNmmrfUx6pAMbiGpKoBLPM7nnr2kC7GqET2ObCJgmoipHFHo5AguVsdc0zqWroD8YqmCNPV9Y9kuIIH",
	"u8OOdyrXu3Y24PDRZ3dEsxyxvAClpfCD1XA3WPWcfuQU0niAn24yFiPH6l7XyNDqBacx+AzZyPU3jroT",
	"kGAfWQPs0io/bam+hQ6bi3y1EGQG1lkhQIL1QdZ6CvwrC5l1jVSngGltKmnZ9Kmiu+XlFYysQbk9+96J",
	"0dwp+fo7KsDsnM6f9mNrKFX7kEGkhK1roF5ZLbbA8jx0kmkzdNGcjoar617GSmBOS27s6eeme1f9+r41",
	"1LcGqc4/yV5Ob8nRi/0NKtgzybAaY3sly+lx9GKLUg8ZNb07GBuyhLPApgTxBAdQuDc/wU09LKvYcTC9",
	"Wg7WzQHtwF4Taq/749tD8r51q8gP9Am1I2xF58aOBpl251atm0bdC1+lMIwTZro3k64ZdUWzHenW9DBc",
	"lxCqIPMNyI8yWXw11PRv8S+7w2NMBMsHhq2/Ax1ACv5aW7+P0r+070uooU81OJybW/gOBEcns4w+s2S5",
	"Kb1Y5sBwQJW4D5XZgjCjyfR0U7qwlcbWts6uZxcKFCzs8RQrO+B3E88+f0goWelYnsxlKVb7KzvMrd1m",
	"LR2gS2riLNByWubShAoCt0zbGsGx5lvkwy4JYjntqc5kwJR/8tzxoS0vNGFKgT3lQR6VInZ3WquTYvun",
	"XxnVpKBaQzIk0zn5rXVC/Ztdont23FUip4vWGTJSsrSaxcArKajJXinsDQRchwFP9hsKd8fbmsB8DrFh",
	"1xDga7TWN4b5108R/RsGjy9F+NPRv1NEN0U8eDP0UqoZSxIQ5MASTX0npLk7/G1obtfE6MDtiXCnpDhq",
	"XQTarQFrv1DfVq7HXtXFfZN5esStl2bNRS9Xl/pbbFiZVg/brqq6ACVVAqorV7NUYNNXkD177WvfVrD4",
	"cE5vf63+/oWznAUK0U72Pm/v/4ll8p1mbqGLpncYwXXM/vh7rEcdntamFkBFF3WBUqXc0NhJ5VPEukHI",
	"dzoYbmvCNZD6y8cUIQ9ZBAQvhH6DiqD71xYB3AUv/v5dKDw9ErgAEwzOULq266rrcKydyZhyksA1cFnk",
	"IIy/WhwNolJxf19tMhpxfC6T2kx+GP8wjpZXy/8HAAD//5kU9zHhQgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
