//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ParticipationStatus1.
const (
	Waitlisted ParticipationStatus1 = "waitlisted"
)

// Defines values for ParticipationStatusUpdate.
const (
	Going    ParticipationStatusUpdate = "going"
	NotGoing ParticipationStatusUpdate = "not_going"
)

// Defines values for UpdateGameParticipationRequestConfirmed.
const (
	True UpdateGameParticipationRequestConfirmed = true
)

// Defines values for GetApiAuthProviderCallbackParamsProvider.
const (
	GetApiAuthProviderCallbackParamsProviderGoogle GetApiAuthProviderCallbackParamsProvider = "google"
)

// Defines values for GetApiAuthProviderLoginParamsProvider.
const (
	GetApiAuthProviderLoginParamsProviderGoogle GetApiAuthProviderLoginParamsProvider = "google"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// ExpiresIn Token expiration time in seconds
	ExpiresIn *int `json:"expiresIn,omitempty"`

	// RefreshToken Optional refresh token for obtaining new access tokens
	RefreshToken *string `json:"refreshToken,omitempty"`

	// Token JWT or session token for authenticating subsequent requests
	Token string `json:"token"`
	User  User   `json:"user"`
}

// CreateGameRequest defines model for CreateGameRequest.
type CreateGameRequest struct {
	// Description Description of the game
	Description *string `json:"description,omitempty"`

	// DurationMinutes Duration of the game in minutes
	DurationMinutes *int64 `json:"durationMinutes,omitempty"`

	// GameSpotsLeft Number of spots left in the game, excluding the waitlist
	GameSpotsLeft *int64 `json:"gameSpotsLeft,omitempty"`

	// Location Location where the game will be held
	Location *string `json:"location,omitempty"`

	// MaxGuestsPerPlayer Maximum guests per player (0 to disable)
	MaxGuestsPerPlayer *int64 `json:"maxGuestsPerPlayer,omitempty"`

	// MaxPlayers Maximum number of players (must be at least 1)
	MaxPlayers *int64 `json:"maxPlayers,omitempty"`

	// Name Name of the game
	Name string `json:"name"`

	// StartsAt When the game starts
	StartsAt *time.Time `json:"startsAt,omitempty"`

	// TotalPriceCents Total price in cents
	TotalPriceCents *int64 `json:"totalPriceCents,omitempty"`
}

// Error Error message string
type Error = string

// Game defines model for Game.
type Game struct {
	// CreatedAt Timestamp when game was created
	CreatedAt time.Time `json:"createdAt"`

	// Description Description of the game
	Description *string `json:"description,omitempty"`

	// DurationMinutes Duration of the game in minutes
	DurationMinutes *int64 `json:"durationMinutes,omitempty"`

	// GameSpotsLeft Number of spots left in the game, excluding the waitlist
	GameSpotsLeft *int64 `json:"gameSpotsLeft,omitempty"`

	// Id Unique game identifier
	Id string `json:"id"`

	// Location Location where the game will be held
	Location *string `json:"location,omitempty"`

	// LockedAt When the game is locked
	LockedAt *time.Time `json:"lockedAt,omitempty"`

	// MaxGuestsPerPlayer Maximum guests per player (0 to disable)
	MaxGuestsPerPlayer *int64 `json:"maxGuestsPerPlayer,omitempty"`

	// MaxPlayers Maximum number of players (must be at least 1)
	MaxPlayers *int64 `json:"maxPlayers,omitempty"`

	// Name Name of the game
	Name string `json:"name"`

	// OrganizerId ID of the user who organized the game
	OrganizerId int `json:"organizerId"`

	// PublishedAt When the game is published (visible to others)
	PublishedAt *time.Time `json:"publishedAt,omitempty"`

	// StartsAt When the game starts
	StartsAt *time.Time `json:"startsAt,omitempty"`

	// TotalPriceCents Total price in cents
	TotalPriceCents *int64 `json:"totalPriceCents,omitempty"`

	// UpdatedAt Timestamp when game was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// GameDetail defines model for GameDetail.
type GameDetail struct {
	Game      Game `json:"game"`
	Organizer User `json:"organizer"`
}

// GameFields defines model for GameFields.
type GameFields struct {
	// Description Description of the game
	Description *string `json:"description,omitempty"`

	// DurationMinutes Duration of the game in minutes
	DurationMinutes *int64 `json:"durationMinutes,omitempty"`

	// GameSpotsLeft Number of spots left in the game, excluding the waitlist
	GameSpotsLeft *int64 `json:"gameSpotsLeft,omitempty"`

	// Location Location where the game will be held
	Location *string `json:"location,omitempty"`

	// MaxGuestsPerPlayer Maximum guests per player (0 to disable)
	MaxGuestsPerPlayer *int64 `json:"maxGuestsPerPlayer,omitempty"`

	// MaxPlayers Maximum number of players (must be at least 1)
	MaxPlayers *int64 `json:"maxPlayers,omitempty"`

	// Name Name of the game
	Name *string `json:"name,omitempty"`

	// StartsAt When the game starts
	StartsAt *time.Time `json:"startsAt,omitempty"`

	// TotalPriceCents Total price in cents
	TotalPriceCents *int64 `json:"totalPriceCents,omitempty"`
}

// GameListItem defines model for GameListItem.
type GameListItem struct {
	// Id Unique game identifier
	Id string `json:"id"`

	// IsOrganizer Whether the authenticated user is the organizer of this game
	IsOrganizer bool `json:"isOrganizer"`

	// Location Location where the game will be held
	Location *string `json:"location,omitempty"`

	// Name Name of the game
	Name      string `json:"name"`
	Organizer User   `json:"organizer"`

	// PublishedAt When the game is published (visible to others)
	PublishedAt nullable.Nullable[time.Time] `json:"publishedAt,omitempty"`

	// StartsAt When the game starts
	StartsAt nullable.Nullable[time.Time] `json:"startsAt,omitempty"`

	// UpdatedAt Timestamp when game was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// GameListResponse defines model for GameListResponse.
type GameListResponse struct {
	// Items Array of games for the current page
	Items []GameListItem `json:"items"`

	// Page Current page number (1-based)
	Page int `json:"page"`

	// PageSize Number of items per page
	PageSize int `json:"pageSize"`

	// Total Total number of items
	Total int `json:"total"`
}

// GameParticipation defines model for GameParticipation.
type GameParticipation struct {
	// CreatedAt Timestamp when the participation record was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// GameId Identifier of the game
	GameId string `json:"gameId"`

	// Status Participation status of the authenticated user
	Status ParticipationStatus `json:"status"`

	// UpdatedAt Timestamp when the participation record was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// UserId Identifier of the participant
	UserId string `json:"userId"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// Page Current page number (1-based)
	Page int `json:"page"`

	// PageSize Number of items per page
	PageSize int `json:"pageSize"`

	// Total Total number of items
	Total int `json:"total"`
}

// ParticipantWithUser defines model for ParticipantWithUser.
type ParticipantWithUser struct {
	// CreatedAt Timestamp when the participation record was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Guests Number of guests the participant is bringing
	Guests int `json:"guests"`

	// Status Participation status of the authenticated user
	Status ParticipationStatus `json:"status"`

	// UpdatedAt Timestamp when the participation record was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	User      User       `json:"user"`
}

// ParticipationStatus Participation status of the authenticated user
type ParticipationStatus struct {
	union json.RawMessage
}

// ParticipationStatus1 defines model for ParticipationStatus.1.
type ParticipationStatus1 string

// ParticipationStatusUpdate Allowed participation statuses that a user can set directly
type ParticipationStatusUpdate string

// PublicGameDetail defines model for PublicGameDetail.
type PublicGameDetail struct {
	union json.RawMessage
}

// PublicGameDetail0 Published game with available spots and start time
type PublicGameDetail0 struct {
	// GameSpotsLeft Number of spots left in the game
	GameSpotsLeft int64 `json:"gameSpotsLeft"`

	// Id Unique game identifier
	Id string `json:"id"`

	// Name Name of the game
	Name      string `json:"name"`
	Organizer struct {
		// Name Organizer's full name
		Name string `json:"name"`

		// Picture URL to organizer's profile picture
		Picture *string `json:"picture,omitempty"`
	} `json:"organizer"`

	// StartsAt When the game starts
	StartsAt time.Time `json:"startsAt"`
}

// PublicGameDetail1 Unpublished game with scheduled publish time
type PublicGameDetail1 struct {
	// Id Unique game identifier
	Id string `json:"id"`

	// Name Name of the game
	Name      string `json:"name"`
	Organizer struct {
		// Name Organizer's full name
		Name string `json:"name"`

		// Picture URL to organizer's profile picture
		Picture *string `json:"picture,omitempty"`
	} `json:"organizer"`

	// PublishedAt When the game will be published
	PublishedAt time.Time `json:"publishedAt"`
}

// ReimbursementRecord defines model for ReimbursementRecord.
type ReimbursementRecord struct {
	// CreatedAt Timestamp when the reimbursement record was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// GameId ID of the game
	GameId string `json:"gameId"`

	// ParticipantId ID of the participant
	ParticipantId string `json:"participantId"`

	// ReimbursedAt When the participant sent the reimbursement
	ReimbursedAt nullable.Nullable[time.Time] `json:"reimbursed_at,omitempty"`

	// ReimbursementReceivedAt When the organizer received and confirmed the reimbursement
	ReimbursementReceivedAt nullable.Nullable[time.Time] `json:"reimbursement_received_at,omitempty"`

	// UpdatedAt Timestamp when the reimbursement record was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// UpdateGameParticipationRequest defines model for UpdateGameParticipationRequest.
type UpdateGameParticipationRequest struct {
	// Confirmed If the participant has confirmed (can only be set to false by the server when important details are changed on the game)
	Confirmed *UpdateGameParticipationRequestConfirmed `json:"confirmed,omitempty"`

	// Guests Number of guests the participant is bringing
	Guests *int `json:"guests,omitempty"`

	// Status Allowed participation statuses that a user can set directly
	Status ParticipationStatusUpdate `json:"status"`
}

// UpdateGameParticipationRequestConfirmed If the participant has confirmed (can only be set to false by the server when important details are changed on the game)
type UpdateGameParticipationRequestConfirmed bool

// UpdateGameRequest defines model for UpdateGameRequest.
type UpdateGameRequest struct {
	// Description Description of the game
	Description *string `json:"description,omitempty"`

	// DurationMinutes Duration of the game in minutes
	DurationMinutes *int64 `json:"durationMinutes,omitempty"`

	// GameSpotsLeft Number of spots left in the game, excluding the waitlist
	GameSpotsLeft *int64 `json:"gameSpotsLeft,omitempty"`

	// Location Location where the game will be held
	Location *string `json:"location,omitempty"`

	// LockedAt When the game should become locked. Past timestamps lock immediately. It can be rescheduled or cleared.
	LockedAt nullable.Nullable[time.Time] `json:"lockedAt,omitempty"`

	// MaxGuestsPerPlayer Maximum guests per player (0 to disable)
	MaxGuestsPerPlayer *int64 `json:"maxGuestsPerPlayer,omitempty"`

	// MaxPlayers Maximum number of players (must be at least 1)
	MaxPlayers *int64 `json:"maxPlayers,omitempty"`

	// Name Name of the game
	Name *string `json:"name,omitempty"`

	// PublishedAt When the game should become publicly visible. Past timestamps publish immediately. While in the future, it can be rescheduled or cleared.
	PublishedAt nullable.Nullable[time.Time] `json:"publishedAt,omitempty"`

	// StartsAt When the game starts
	StartsAt *time.Time `json:"startsAt,omitempty"`

	// TotalPriceCents Total price in cents
	TotalPriceCents *int64 `json:"totalPriceCents,omitempty"`
}

// UpdateReimbursementRequest defines model for UpdateReimbursementRequest.
type UpdateReimbursementRequest struct {
	union json.RawMessage
}

// UpdateReimbursementRequest0 Organizer request - update a participant's reimbursement status
type UpdateReimbursementRequest0 struct {
	// ParticipantId ID of the participant to update reimbursement for
	ParticipantId string `json:"participantId"`

	// ReimbursementReceivedAt When the organizer received and confirmed the reimbursement. Set to null to clear.
	ReimbursementReceivedAt nullable.Nullable[time.Time] `json:"reimbursement_received_at,omitempty"`
}

// UpdateReimbursementRequest1 Participant request - set their own reimbursement date
type UpdateReimbursementRequest1 struct {
	// ReimbursedAt When the participant sent the reimbursement. Set to null to clear.
	ReimbursedAt nullable.Nullable[time.Time] `json:"reimbursed_at"`
}

// User defines model for User.
type User struct {
	// CreatedAt Timestamp when user was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Email User's email address
	Email openapi_types.Email `json:"email"`

	// Id Unique user identifier
	Id string `json:"id"`

	// IsDemo Whether the user is a demo user
	IsDemo bool `json:"isDemo"`

	// Name User's full name
	Name *string `json:"name,omitempty"`

	// Picture URL to user's profile picture
	Picture *string `json:"picture,omitempty"`

	// UpdatedAt Timestamp when user was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// GetApiAuthProviderCallbackParams defines parameters for GetApiAuthProviderCallback.
type GetApiAuthProviderCallbackParams struct {
	// Code Authorization code returned by the provider on success
	Code *string `form:"code,omitempty" json:"code,omitempty"`

	// State State parameter for CSRF protection
	State *string `form:"state,omitempty" json:"state,omitempty"`

	// Error Error code if authorization failed
	Error *string `form:"error,omitempty" json:"error,omitempty"`

	// ErrorDescription Human-readable error description
	ErrorDescription *string `form:"error_description,omitempty" json:"error_description,omitempty"`
}

// GetApiAuthProviderCallbackParamsProvider defines parameters for GetApiAuthProviderCallback.
type GetApiAuthProviderCallbackParamsProvider string

// GetApiAuthProviderLoginParamsProvider defines parameters for GetApiAuthProviderLogin.
type GetApiAuthProviderLoginParamsProvider string

// GetApiGamesParams defines parameters for GetApiGames.
type GetApiGamesParams struct {
	// Page Page number (1-based) for pagination
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of games per page (max 25)
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PostApiGamesJSONRequestBody defines body for PostApiGames for application/json ContentType.
type PostApiGamesJSONRequestBody = CreateGameRequest

// PatchApiGamesIdJSONRequestBody defines body for PatchApiGamesId for application/json ContentType.
type PatchApiGamesIdJSONRequestBody = UpdateGameRequest

// PutApiGamesIdParticipantsJSONRequestBody defines body for PutApiGamesIdParticipants for application/json ContentType.
type PutApiGamesIdParticipantsJSONRequestBody = UpdateGameParticipationRequest

// PutApiGamesIdReimbursementsJSONRequestBody defines body for PutApiGamesIdReimbursements for application/json ContentType.
type PutApiGamesIdReimbursementsJSONRequestBody = UpdateReimbursementRequest

// AsParticipationStatusUpdate returns the union data inside the ParticipationStatus as a ParticipationStatusUpdate
func (t ParticipationStatus) AsParticipationStatusUpdate() (ParticipationStatusUpdate, error) {
	var body ParticipationStatusUpdate
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromParticipationStatusUpdate overwrites any union data inside the ParticipationStatus as the provided ParticipationStatusUpdate
func (t *ParticipationStatus) FromParticipationStatusUpdate(v ParticipationStatusUpdate) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeParticipationStatusUpdate performs a merge with any union data inside the ParticipationStatus, using the provided ParticipationStatusUpdate
func (t *ParticipationStatus) MergeParticipationStatusUpdate(v ParticipationStatusUpdate) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsParticipationStatus1 returns the union data inside the ParticipationStatus as a ParticipationStatus1
func (t ParticipationStatus) AsParticipationStatus1() (ParticipationStatus1, error) {
	var body ParticipationStatus1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromParticipationStatus1 overwrites any union data inside the ParticipationStatus as the provided ParticipationStatus1
func (t *ParticipationStatus) FromParticipationStatus1(v ParticipationStatus1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeParticipationStatus1 performs a merge with any union data inside the ParticipationStatus, using the provided ParticipationStatus1
func (t *ParticipationStatus) MergeParticipationStatus1(v ParticipationStatus1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ParticipationStatus) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ParticipationStatus) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPublicGameDetail0 returns the union data inside the PublicGameDetail as a PublicGameDetail0
func (t PublicGameDetail) AsPublicGameDetail0() (PublicGameDetail0, error) {
	var body PublicGameDetail0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPublicGameDetail0 overwrites any union data inside the PublicGameDetail as the provided PublicGameDetail0
func (t *PublicGameDetail) FromPublicGameDetail0(v PublicGameDetail0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePublicGameDetail0 performs a merge with any union data inside the PublicGameDetail, using the provided PublicGameDetail0
func (t *PublicGameDetail) MergePublicGameDetail0(v PublicGameDetail0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPublicGameDetail1 returns the union data inside the PublicGameDetail as a PublicGameDetail1
func (t PublicGameDetail) AsPublicGameDetail1() (PublicGameDetail1, error) {
	var body PublicGameDetail1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPublicGameDetail1 overwrites any union data inside the PublicGameDetail as the provided PublicGameDetail1
func (t *PublicGameDetail) FromPublicGameDetail1(v PublicGameDetail1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePublicGameDetail1 performs a merge with any union data inside the PublicGameDetail, using the provided PublicGameDetail1
func (t *PublicGameDetail) MergePublicGameDetail1(v PublicGameDetail1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PublicGameDetail) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PublicGameDetail) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsUpdateReimbursementRequest0 returns the union data inside the UpdateReimbursementRequest as a UpdateReimbursementRequest0
func (t UpdateReimbursementRequest) AsUpdateReimbursementRequest0() (UpdateReimbursementRequest0, error) {
	var body UpdateReimbursementRequest0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUpdateReimbursementRequest0 overwrites any union data inside the UpdateReimbursementRequest as the provided UpdateReimbursementRequest0
func (t *UpdateReimbursementRequest) FromUpdateReimbursementRequest0(v UpdateReimbursementRequest0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUpdateReimbursementRequest0 performs a merge with any union data inside the UpdateReimbursementRequest, using the provided UpdateReimbursementRequest0
func (t *UpdateReimbursementRequest) MergeUpdateReimbursementRequest0(v UpdateReimbursementRequest0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUpdateReimbursementRequest1 returns the union data inside the UpdateReimbursementRequest as a UpdateReimbursementRequest1
func (t UpdateReimbursementRequest) AsUpdateReimbursementRequest1() (UpdateReimbursementRequest1, error) {
	var body UpdateReimbursementRequest1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUpdateReimbursementRequest1 overwrites any union data inside the UpdateReimbursementRequest as the provided UpdateReimbursementRequest1
func (t *UpdateReimbursementRequest) FromUpdateReimbursementRequest1(v UpdateReimbursementRequest1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUpdateReimbursementRequest1 performs a merge with any union data inside the UpdateReimbursementRequest, using the provided UpdateReimbursementRequest1
func (t *UpdateReimbursementRequest) MergeUpdateReimbursementRequest1(v UpdateReimbursementRequest1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t UpdateReimbursementRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *UpdateReimbursementRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Logout the authenticated user
	// (POST /api/auth/logout)
	PostApiAuthLogout(w http.ResponseWriter, r *http.Request)
	// Get authenticated user
	// (GET /api/auth/me)
	GetApiAuthMe(w http.ResponseWriter, r *http.Request)
	// OAuth callback endpoint
	// (GET /api/auth/{provider}/callback)
	GetApiAuthProviderCallback(w http.ResponseWriter, r *http.Request, provider GetApiAuthProviderCallbackParamsProvider, params GetApiAuthProviderCallbackParams)
	// Initiate OAuth login with a provider
	// (GET /api/auth/{provider}/login)
	GetApiAuthProviderLogin(w http.ResponseWriter, r *http.Request, provider GetApiAuthProviderLoginParamsProvider)
	// List demo users
	// (GET /api/demo/users)
	GetApiDemoUsers(w http.ResponseWriter, r *http.Request)
	// Impersonate a demo user
	// (POST /api/demo/users/{userId}/impersonate)
	PostApiDemoUsersUserIdImpersonate(w http.ResponseWriter, r *http.Request, userId string)
	// List user's games
	// (GET /api/games)
	GetApiGames(w http.ResponseWriter, r *http.Request, params GetApiGamesParams)
	// Create a new game
	// (POST /api/games)
	PostApiGames(w http.ResponseWriter, r *http.Request)
	// Get a game by ID
	// (GET /api/games/{id})
	GetApiGamesId(w http.ResponseWriter, r *http.Request, id string)
	// Update a game
	// (PATCH /api/games/{id})
	PatchApiGamesId(w http.ResponseWriter, r *http.Request, id string)
	// List game participants
	// (GET /api/games/{id}/participants)
	GetApiGamesIdParticipants(w http.ResponseWriter, r *http.Request, id string)
	// Set participation status
	// (PUT /api/games/{id}/participants)
	PutApiGamesIdParticipants(w http.ResponseWriter, r *http.Request, id string)
	// Update reimbursement status for a participant
	// (PUT /api/games/{id}/reimbursements)
	PutApiGamesIdReimbursements(w http.ResponseWriter, r *http.Request, id string)
	// Get public game information
	// (GET /public/api/games/{id})
	GetPublicApiGamesId(w http.ResponseWriter, r *http.Request, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostApiAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostApiAuthLogout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetApiAuthMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAuthProviderCallback operation middleware
func (siw *ServerInterfaceWrapper) GetApiAuthProviderCallback(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "provider" -------------
	var provider GetApiAuthProviderCallbackParamsProvider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiAuthProviderCallbackParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameter("form", true, false, "code", r.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameter("form", true, false, "error", r.URL.Query(), &params.Error)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		return
	}

	// ------------- Optional query parameter "error_description" -------------

	err = runtime.BindQueryParameter("form", true, false, "error_description", r.URL.Query(), &params.ErrorDescription)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error_description", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAuthProviderCallback(w, r, provider, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAuthProviderLogin operation middleware
func (siw *ServerInterfaceWrapper) GetApiAuthProviderLogin(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "provider" -------------
	var provider GetApiAuthProviderLoginParamsProvider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAuthProviderLogin(w, r, provider)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiDemoUsers operation middleware
func (siw *ServerInterfaceWrapper) GetApiDemoUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiDemoUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiDemoUsersUserIdImpersonate operation middleware
func (siw *ServerInterfaceWrapper) PostApiDemoUsersUserIdImpersonate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiDemoUsersUserIdImpersonate(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiGames operation middleware
func (siw *ServerInterfaceWrapper) GetApiGames(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiGamesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiGames(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiGames operation middleware
func (siw *ServerInterfaceWrapper) PostApiGames(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiGames(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiGamesId operation middleware
func (siw *ServerInterfaceWrapper) GetApiGamesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiGamesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchApiGamesId operation middleware
func (siw *ServerInterfaceWrapper) PatchApiGamesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchApiGamesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiGamesIdParticipants operation middleware
func (siw *ServerInterfaceWrapper) GetApiGamesIdParticipants(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiGamesIdParticipants(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiGamesIdParticipants operation middleware
func (siw *ServerInterfaceWrapper) PutApiGamesIdParticipants(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiGamesIdParticipants(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiGamesIdReimbursements operation middleware
func (siw *ServerInterfaceWrapper) PutApiGamesIdReimbursements(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiGamesIdReimbursements(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicApiGamesId operation middleware
func (siw *ServerInterfaceWrapper) GetPublicApiGamesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicApiGamesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/auth/logout", wrapper.PostApiAuthLogout)
	m.HandleFunc("GET "+options.BaseURL+"/api/auth/me", wrapper.GetApiAuthMe)
	m.HandleFunc("GET "+options.BaseURL+"/api/auth/{provider}/callback", wrapper.GetApiAuthProviderCallback)
	m.HandleFunc("GET "+options.BaseURL+"/api/auth/{provider}/login", wrapper.GetApiAuthProviderLogin)
	m.HandleFunc("GET "+options.BaseURL+"/api/demo/users", wrapper.GetApiDemoUsers)
	m.HandleFunc("POST "+options.BaseURL+"/api/demo/users/{userId}/impersonate", wrapper.PostApiDemoUsersUserIdImpersonate)
	m.HandleFunc("GET "+options.BaseURL+"/api/games", wrapper.GetApiGames)
	m.HandleFunc("POST "+options.BaseURL+"/api/games", wrapper.PostApiGames)
	m.HandleFunc("GET "+options.BaseURL+"/api/games/{id}", wrapper.GetApiGamesId)
	m.HandleFunc("PATCH "+options.BaseURL+"/api/games/{id}", wrapper.PatchApiGamesId)
	m.HandleFunc("GET "+options.BaseURL+"/api/games/{id}/participants", wrapper.GetApiGamesIdParticipants)
	m.HandleFunc("PUT "+options.BaseURL+"/api/games/{id}/participants", wrapper.PutApiGamesIdParticipants)
	m.HandleFunc("PUT "+options.BaseURL+"/api/games/{id}/reimbursements", wrapper.PutApiGamesIdReimbursements)
	m.HandleFunc("GET "+options.BaseURL+"/public/api/games/{id}", wrapper.GetPublicApiGamesId)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xce2/buJb/KlztAtMCru2k7eCu/9rcZNvrIr0NkuZ2gUFQ0NKxzSlFqiSVxFP4uy8O",
	"ScmURL/yaNO5889MbUs8h+fxOw8e5luSyryQAoTRyehbotM55NT+86g083PQhRQa8HOhZAHKMLC/wm3B",
	"FOixwA8Z6FSxwjApklHyUX4BQewDFL8ihuVAmCAaUikynfQSuKV5wSEZvfx1OOwlZlFAMkqYMDADlSx7",
	"iYKpAj23S3UpfLD/oJz4x4ixJKdSETkxlAkmZkTADaFpClq7n5GuJ6SNYmKGdEycwLtPH4lURIPWdgP1",
	"8rQ0cxCGpdQgDV1ONHwtQRii8P/aNHaXwOLdfPI2ZR/Yu/HlH+ODf7KxHovz1+nx+Nfxl+L//nX87r/7",
	"/X6Ms1KDQsb+S8E0GSX/OVgpauC1NLjEZ5ZWXF9LpiBLRr/5LfkFruqV5eR3SA2ufKyAGnhLczh3PCMZ",
	"yvmHaTL6bTNBfOkNA57pZNn71iAraA4RclfLXvK/SknVFbL9muSgNZ0B8TuPSAKJ3pnFptWmduvZkYlY",
	"LctBG5oX5GYOgsxoDuSGauJfSXrJVKqcmmSUZNTACzTqGLcs6659KdjXEtyaLEP7mTJQDUuhf08PYstx",
	"mX6JM/wJ2TTzallN3KM7MyrVjAr2B6hxhOPxCZFTuzqaEbmZS1I9n9VEww0cHL589TrmyUU54UzPd9xD",
	"/TR5ds00m3AgRhJp5qD08523VhbZvmrmVBvi39uRTsvvGL4XCrUXmFvIU2+Tr6D5noChjHcxd+YdYZv5",
	"N7R7Jwzx2l0tEsORwNM6rDaE3tbByepTZWVtc0rGIpNSkWvJOSwmlHPyguB/OVwD1+QGeCpz+I+kl+T0",
	"9hTEzMyT0cEwiCYrc8hKF4jeM1GaCH/JiX8g5AYDVu5faNj5MLAOJsyvr5KY2eMSF4U0+hSmETP8Z5lP",
	"QCE9jQ8RDlODFCvqPQK3KS8zDDL43Q1lhjNtGqzEOMmZYHmZJ6NoWOUypXGdnPpf0C0UrKRwwzgnEyBz",
	"4FlDQQeHL8l7ygS5MD1yIm+EkTci5ow5vX1rI+MZqDNOFxAJBe/pLXJNZvZBUoAihX2UPBsiAGRM0wmH",
	"5yEHh3vvPqe3jgG9ngNRK8YxoMmzvNQGRUAN4YAwcfC8aRGbGDmIMSK8I7dsAuW9zh8uSpHRBXkvlU1u",
	"/lX7RccDLPH6c0Qh2lBl9HY4ds/tDLpGGsrPFEvhuMom23mhoZwU+ASaemqfCgX5eriLby3XQNEp02Zs",
	"IO+C0QOHZKY/hODaESEGKyvFIFmEzAVSpu0vNbA6fTPdUbhRJdS0J1JyoOJHefADm+v6TGS3WPVdcgpR",
	"co6Q09LEQ3vRVjI/LpURTqehtYeqClm72uCSYQm5WwZ/RmdMOCPvZvDMQB7BliOl6AKtEaWgbamGGkhL",
	"pbA4K+jM7qV6eVsGVWPJCmwoUuhKyq64PpU7o8qwlBW1z961HsHdFOFiREEqVXanGgWFFM36ayBsOXbM",
	"+k25VZSN3V+4V/ay6Y27voOdu6p4t63XdIXZ6jBeHPXytYhjnhHYd8cgrKF2mDsOzLjKUJ4dvJhQDVkz",
	"F4lWYHQGF+wP2JSFWjt2eZdzlUaW2V3TBvt1IV40lw1Xe3UYDejN/gUu7dhOAu7joqx19ImZ+aXvmTwN",
	"J3PtoA1C99luy9gwZE1wkUY7JJD9T+17dypHG+6V1KLdaBHBtjs7bTxE3OqV23eTNgx7AnYKXB3al1ZE",
	"No6BwHrgt6Qq5SBEh0pIV/Et+GW6YY9zeQNZS09uQ4CWRQ2hLvNMqSAaDMmYgtTwBXql52gmnakJaT67",
	"f19FtHeGaVTa7E+s5NIScJ1y+RTUzAm9pszmOr7kpSJzyRHx9tJtdtyjgL5nofzAJcN3zaCbcoyTrnO6",
	"XzSZlpwT0ab/Ts4FOZFRRy5YakoVWfby/NTm1sHqhZJTxoFU74Q05sYUejQY+G/6qcwH9Joaqvq/F7MQ",
	"V0rFtgbhNV21Ryp4N6TMYZLcNOOAlwijXYMrIn6EaJOVHL3e/Rr3n78s+E9kwXsUvFW5X7/ysPYcchIv",
	"e86B5ZNSachBmHObMtw3J1Phko9S+JxsK3iCBG3zAhvLBpSx30r2mW7SZZgQatx1Rw53bik0VvmsIAV2",
	"vY2dVcOqet7G71SKKVO5PxN6GPb2y1DXmsb9uyBNlW8s6Vx+1in4g/PVlvlXcotYUseMyBwtvZb0M8zk",
	"pOAL9HLM6IwkU8o1kMnCvqpBXdszOxCE5YVUBhfJbNKmCVVA0jkVM8iIXOHG81U+iHq5ivUen15FU6XX",
	"8Xphs6bue/jd1Oiu57R6LkuekQmkMgd/ZNsnZ2isprJud5RLWJ5DxqgBvuiTsbEZ/AQtfpUBSEVSDlRB",
	"1r+zv+0RW5rM2xdTviC+q9rdRpWgNHbyaY7B1Kfq0xJDao+wR9reMhqinBG0AlVtDeuKmg8BBtqHyQsP",
	"MISG5v6LbqFSXb62ez37hxR0dk+zSWMqVfLDsL5PLhwOoTbw/1Zr99DZehjeIW0OmkKBpixSzoEpIm9E",
	"S3gWRNrqebhI/ajiabIZT8nu2xdzMyB3yLcg942CVpKtbWJtfyU0yxTo5twUEvyfIKcOCbo195u8cWdv",
	"8YrHTq7Ez/lOIJebj/iqQz1KMshl1S6qF7dxORZK4zWNl8vDlzOlfuxKZp+8rTanBzqpqizCK6zrA5hi",
	"QFoqZhYXGMyd/U8wsqij0sxXn95ULLz79BGrdfs0qs7+umIHpZUscWEmphEbOTobu3HEAsRsgfZrmLFy",
	"9t+Qo7Nx0kuuQWn3xkF/2B/aSrgAQQuWjJKX9iusPczccjygBRvQ0swHXM5k6RJLqSMSP0aE0e2G5mqW",
	"EQGdy5kmsjS1ISeWuBuFwYiUnEltjgqGIjp1BFH67jzPMnQ4fNWlfVHaqUu04gUSsZlmabOvV8MDn/4a",
	"LBFG3xIDt2ZQcMrEavx0WyLo5gmt9NvejpuVyk6pvSBMXFPObBqRM63tLI0djgwNwgb60BR+u1pe9RJd",
	"5jlVC3uuPquEFO0NGzrTaIpHDTknV0hkpTDn7jOI6OocTKmEDg8s+WJNH7qhnrdQaec9dDUzbEmaFgX3",
	"zA1+13IPefuefEfcR10Wf1IdvwVzH+V+K5S8Zhmo5SClnE9o+mWttv9BRcbBafsDLkuql23e6NrzhE4N",
	"KAeUM0WF0bjBDAQDTar9O1bWG8WZX/e4Ysl2MWgOxk5AdfLbjx2OEFPxFwSgqh00SoJfV1DsUpWVbldn",
	"C3LGIXKg0M3bjsJ9kVRmmEaha0BWlbYVaaxctYOZisevJajFikl8PQkZ2koeK0qbzTkJWfg+vjh/g0QN",
	"pF7YMVqY3+9JzM0+2z2yaVOjZEoZt/EwRgusX+xF6x9lTsULBTSzpy92BRI+soHS5+Zz66lePSL+NG4i",
	"RCChEXBoFJReDg9jwOu9zUgyVZbTzPXYXZCUilTingPN/Nzg6doJrDfVGph1RdbBotcK2VmZ3ijQpYXS",
	"4WNC6dhjZ1Uk1XxOlcxXIPD4mN5E18oBLILXEO2QqYJXAiIrJHM91n0xmsuZY3tNOHZWoVcJvpFxuG76",
	"rR9Y2AbHp5b63ljs0/jOLZSV/z4KSrf9eqsjBeJxG4gKaSd/8sXL7qJ/Et5UK0wXkGK52bbksWCGYaxx",
	"m7LW6I/Iw8i71ayx4hygfeqtqSXlfFWg6jVGisXTpf/9Xli+05hdNcvZGq/riPWUITJNA/YxK1AMriGr",
	"cgCL/A6nXj6mitErEX1e2EBBNRHSuFNjyBDcLY85BnUt3VhvBVOE6WqIPeu37MHusKGdSvWunI0ofPDN",
	"DZotBywvQGkp/HhIvBqsak7fYo1x3MNPN3OWIsbqTtXIUOoFpyn4CLmi6+9NNDsg0TqyNrBLy/w4YH0L",
	"HK56oTURRAbWWCECgvU43noI/J6JzLpCqpHABJvKApn+rNYdaLllI2us3E7w7oRobtZ3/aQ9MNun8/1s",
	"LA2lCkelxIywdQXUW8vFFrM8i81j2ghdrGY849l1J2JlMKUlN3aGc9PtkW5+Hxy/WYFUU5zkWU5vyeHr",
	"5xtYsJOVcTaG9mKJ4+Pw9RamHtNrOpPkG6KEk8CmAPETNqBwb76DO/NmWfmOM9OrZW9dH9A27DWh9jo0",
	"vt0nH4O7Eb6hT6htYSs6NbY1yLQ7YQ7uSzRPhkphGCfMNO9XXDPqkmZ3QlXBQ39dQKiczBcgf5fZ4sGs",
	"pnvLedlsHmMgWD6y2fpJyYil4K+19LtW+l3rvowa+rM6h1NzYN8R52hElsE3li03hReLHOgOyBL3rjJZ",
	"EGY0GZ9sChc209ha1tn17EKRhIU9nWRlB/vdhLOvHtOULHVMT6ayFO36yjZza7VZSUfgkpp0Hik5LXJp",
	"QgWBW6ZtjuBQ8wPiYRMEMZ32UOdOlt2TfvjZpheaMKXAnvIgjkqRgjUkmE4hNewa3B/HmFNNCqo1ZH1y",
	"KtMv+G6VrFfTEL1wNKLXmo1owStu7gdb5cMjend05+khuj/M/AvRm4j+6LXLG6kmLMtAkBcWF+qRpdXs",
	"6o9BpV3j2GU1SLRzDBsEgye71UvhC/UVybpLFYyYOzTDrZdmze0Sl0b6qzOYSFYP2yKomiyUKgPVpKvZ",
	"TGCNVpBn9q7Jc5tw4sM5vf1cXbrnLGeRvLERbM/C/f9kgXenFlnsdtseHbOG2J9+SfSk3dPK1BpQ0bS6",
	"SGZRbqjDpPIhYl3f4hcddbc17hoJ/eVT8pDHTAKik9Y/ICNoXvGO2F30tuFficLPBwIXYKLOuVu4boyE",
	"ugHgGFJcxqZ7jaKuKLCnfx0g6pN6NllXR0ikMTfrJnj9FdC1Q8F9ctYI1fGRWXzS5gmyNJ4astagtwWY",
	"zpuy+DNBU3Sq/DvDUuwKVsQXziNT6k8JmBrteusFGPeMJEykvOyY+JQBz/7tq57gTws1pecyCNa6nPC9",
	"ILfFzP2qpNj1Cg+Nret3EVh211b2bwjakqS6dZsSJty4MoYBOkEopL7/M57G//xQz4+z6fDKevMWvH0Z",
	"ZbPAUNN90d3pMt1LntFSyd3Y/3N2Jzt/jSCWeDlN+b/mt1LX021bFnGOY5Zs3UZdxzV5KlPKSQbXwGXh",
	"nMQ+m/SSUnE/vz4aDDg+N5fajP42/NswWV4t/z8AAP//KSCLHhFYAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
